<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>
  <link rel="icon" type="image/x-icon" href="../favicon.ico">

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Apêndice F — Análise de Percepção e Avaliação Didática: PDI-VC 2026.2 – Processamento Digital de Imagens e Visão Computacional</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../apendice_e_ia_avaliacao.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d024cad0e32bf2110a1b02cbacc0c8bd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,300..900;1,8..60,300..900&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">

<script>
document.addEventListener('DOMContentLoaded', function() {
  // 1. Botão flutuante na esquerda (menu lateral)
  const btnSidebar = document.createElement('button');
  btnSidebar.id = 'toggle-sidebar-btn';
  btnSidebar.className = 'toggle-layout-btn';
  btnSidebar.innerHTML = '◀';
  btnSidebar.title = 'Esconder/Mostrar Menu Lateral';
  document.body.appendChild(btnSidebar);

  btnSidebar.addEventListener('click', function() {
    document.body.classList.toggle('sidebar-hidden');
    btnSidebar.innerHTML = document.body.classList.contains('sidebar-hidden') ? '▶' : '◀';
  });

  // 2. Botão flutuante na direita (índice / TOC), mesmo espaçamento do botão esquerdo
  const btnToc = document.createElement('button');
  btnToc.id = 'toggle-toc-btn';
  btnToc.className = 'toggle-layout-btn';
  btnToc.innerHTML = '▶';
  btnToc.title = 'Esconder/Mostrar Índice';
  document.body.appendChild(btnToc);

  btnToc.addEventListener('click', function() {
    document.body.classList.toggle('toc-hidden');
    btnToc.innerHTML = document.body.classList.contains('toc-hidden') ? '◀' : '▶';
  });
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../apendice_a_mctest.html">Apêndices</a></li><li class="breadcrumb-item"><a href="../apendice_f/apendice_f.html"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Análise de Percepção e Avaliação Didática: PDI-VC 2026.2</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Processamento Digital de Imagens e Visão Computacional</a> 
        <div class="sidebar-tools-main">
    <a href="../livro.pt.py.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PDI e VC — Python</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ficha_catalografica.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ficha Catalográfica</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../prefacio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I — Fundamentos de PDI</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap01/cap01.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Fundamentos e Primeiros Passos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap02/cap02.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Da Captura ao Pixel - Amostragem, Quantização e Conectividade</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap03/cap03.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Operações Espaciais: Intensidade, Histograma e Filtragem</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap04/cap04.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Morfologia Matemática e Segmentação de Imagens</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap05/cap05.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transformadas e Compressão</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II — Visão Computacional</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap06/cap06.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Análise de Documentos e Inspeção Industrial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap07/cap07.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Classificação de Imagens e Reconhecimento de Padrões</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap08/cap08.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Compreendendo Cenas: Correspondência de Características, Detecção e Segmentação</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../cap09/cap09.py.pt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Aprendizado Profundo para Visão Computacional</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendice_a_mctest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Sobre o MCTest</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendice_b_moodle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Sobre o Moodle (VPL)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendice_c_seb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Uso do SEB nos simulados quinzenais e avaliações</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendice_d_gemini_notebook.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Geração de material didático com o <em>Gemini Notebook</em></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendice_e_ia_avaliacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Uso de IA na Avaliação de Estudantes: o Projeto vpl-ai-feedback</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../apendice_f/apendice_f.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Análise de Percepção e Avaliação Didática: PDI-VC 2026.2</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#caracterização-da-amostra-e-metodologia-de-coleta" id="toc-caracterização-da-amostra-e-metodologia-de-coleta" class="nav-link active" data-scroll-target="#caracterização-da-amostra-e-metodologia-de-coleta"><span class="header-section-number">F.1</span> Caracterização da Amostra e Metodologia de Coleta</a></li>
  <li><a href="#itens-do-questionário-pós" id="toc-itens-do-questionário-pós" class="nav-link" data-scroll-target="#itens-do-questionário-pós"><span class="header-section-number">F.2</span> Itens do questionário PÓS</a>
  <ul class="collapse">
  <li><a href="#itens-do-bloco-2-autopercepção-de-aprendizado-e-desempenho" id="toc-itens-do-bloco-2-autopercepção-de-aprendizado-e-desempenho" class="nav-link" data-scroll-target="#itens-do-bloco-2-autopercepção-de-aprendizado-e-desempenho"><span class="header-section-number">F.2.1</span> Itens do Bloco 2 — Autopercepção de Aprendizado e Desempenho</a></li>
  <li><a href="#itens-do-bloco-3-recursos-didáticos" id="toc-itens-do-bloco-3-recursos-didáticos" class="nav-link" data-scroll-target="#itens-do-bloco-3-recursos-didáticos"><span class="header-section-number">F.2.2</span> Itens do Bloco 3 — Recursos Didáticos</a></li>
  <li><a href="#itens-do-bloco-4-avaliação-específica-do-uso-transversal-da-inteligência-artificial" id="toc-itens-do-bloco-4-avaliação-específica-do-uso-transversal-da-inteligência-artificial" class="nav-link" data-scroll-target="#itens-do-bloco-4-avaliação-específica-do-uso-transversal-da-inteligência-artificial"><span class="header-section-number">F.2.3</span> Itens do Bloco 4 — Avaliação Específica do Uso Transversal da Inteligência Artificial</a></li>
  <li><a href="#bloco-5-questões-abertas" id="toc-bloco-5-questões-abertas" class="nav-link" data-scroll-target="#bloco-5-questões-abertas"><span class="header-section-number">F.2.4</span> Bloco 5 — Questões Abertas</a></li>
  </ul></li>
  <li><a href="#perfil-acadêmico-dos-participantes" id="toc-perfil-acadêmico-dos-participantes" class="nav-link" data-scroll-target="#perfil-acadêmico-dos-participantes"><span class="header-section-number">F.3</span> Perfil acadêmico dos participantes</a></li>
  <li><a href="#sec-pre-pos" id="toc-sec-pre-pos" class="nav-link" data-scroll-target="#sec-pre-pos"><span class="header-section-number">F.4</span> Comparação entre os Questionários PRÉ e PÓS</a>
  <ul class="collapse">
  <li><a href="#evolução-da-percepção-dos-estudantes-pré-versus-pós" id="toc-evolução-da-percepção-dos-estudantes-pré-versus-pós" class="nav-link" data-scroll-target="#evolução-da-percepção-dos-estudantes-pré-versus-pós"><span class="header-section-number">F.4.1</span> Evolução da Percepção dos Estudantes: PRÉ versus PÓS</a></li>
  <li><a href="#análise-complementar-entre-as-amostras-completas" id="toc-análise-complementar-entre-as-amostras-completas" class="nav-link" data-scroll-target="#análise-complementar-entre-as-amostras-completas"><span class="header-section-number">F.4.2</span> Análise complementar entre as amostras completas</a></li>
  </ul></li>
  <li><a href="#avaliação-dos-recursos-didáticos-no-pós-teste-de-friedman" id="toc-avaliação-dos-recursos-didáticos-no-pós-teste-de-friedman" class="nav-link" data-scroll-target="#avaliação-dos-recursos-didáticos-no-pós-teste-de-friedman"><span class="header-section-number">F.5</span> Avaliação dos Recursos Didáticos no PÓS — Teste de Friedman</a>
  <ul class="collapse">
  <li><a href="#classificação-dos-recursos-segundo-o-papel-da-ia" id="toc-classificação-dos-recursos-segundo-o-papel-da-ia" class="nav-link" data-scroll-target="#classificação-dos-recursos-segundo-o-papel-da-ia"><span class="header-section-number">F.5.1</span> Classificação dos recursos segundo o papel da IA</a></li>
  <li><a href="#ranking-agregado-por-frequência-de-seleção-dos-recursos" id="toc-ranking-agregado-por-frequência-de-seleção-dos-recursos" class="nav-link" data-scroll-target="#ranking-agregado-por-frequência-de-seleção-dos-recursos"><span class="header-section-number">F.5.2</span> <em>Ranking</em> agregado por frequência de seleção dos recursos</a></li>
  <li><a href="#comparações-múltiplas-pós-teste-de-conover" id="toc-comparações-múltiplas-pós-teste-de-conover" class="nav-link" data-scroll-target="#comparações-múltiplas-pós-teste-de-conover"><span class="header-section-number">F.5.3</span> Comparações múltiplas — Pós-teste de Conover</a></li>
  </ul></li>
  <li><a href="#ranking-agregado-por-frequência-de-seleção-dos-recursos-didáticos-q09" id="toc-ranking-agregado-por-frequência-de-seleção-dos-recursos-didáticos-q09" class="nav-link" data-scroll-target="#ranking-agregado-por-frequência-de-seleção-dos-recursos-didáticos-q09"><span class="header-section-number">F.6</span> <em>Ranking</em> agregado por frequência de seleção dos recursos didáticos — Q09</a></li>
  <li><a href="#avaliação-global-dos-recursos-didáticos-q10" id="toc-avaliação-global-dos-recursos-didáticos-q10" class="nav-link" data-scroll-target="#avaliação-global-dos-recursos-didáticos-q10"><span class="header-section-number">F.7</span> Avaliação Global dos Recursos Didáticos — Q10</a></li>
  <li><a href="#confiabilidade-dos-recursos-didáticos" id="toc-confiabilidade-dos-recursos-didáticos" class="nav-link" data-scroll-target="#confiabilidade-dos-recursos-didáticos"><span class="header-section-number">F.8</span> Confiabilidade dos Recursos Didáticos</a></li>
  <li><a href="#diferenças-entre-turmas" id="toc-diferenças-entre-turmas" class="nav-link" data-scroll-target="#diferenças-entre-turmas"><span class="header-section-number">F.9</span> Diferenças entre Turmas</a></li>
  <li><a href="#uso-transversal-e-integração-da-ia" id="toc-uso-transversal-e-integração-da-ia" class="nav-link" data-scroll-target="#uso-transversal-e-integração-da-ia"><span class="header-section-number">F.10</span> Uso Transversal e Integração da IA</a></li>
  <li><a href="#síntese-dos-resultados" id="toc-síntese-dos-resultados" class="nav-link" data-scroll-target="#síntese-dos-resultados"><span class="header-section-number">F.11</span> Síntese dos Resultados</a>
  <ul class="collapse">
  <li><a href="#tabela-síntese-dos-resultados-estatísticos" id="toc-tabela-síntese-dos-resultados-estatísticos" class="nav-link" data-scroll-target="#tabela-síntese-dos-resultados-estatísticos">Tabela Síntese dos Resultados Estatísticos</a></li>
  </ul></li>
  <li><a href="#principais-conclusões" id="toc-principais-conclusões" class="nav-link" data-scroll-target="#principais-conclusões"><span class="header-section-number">F.12</span> Principais Conclusões</a></li>
  <li><a href="#avaliação-de-valência-das-respostas-abertas-q14-e-q15" id="toc-avaliação-de-valência-das-respostas-abertas-q14-e-q15" class="nav-link" data-scroll-target="#avaliação-de-valência-das-respostas-abertas-q14-e-q15"><span class="header-section-number">F.13</span> Avaliação de Valência das Respostas Abertas — Q14 e Q15</a>
  <ul class="collapse">
  <li><a href="#unidade-de-análise-e-critérios" id="toc-unidade-de-análise-e-critérios" class="nav-link" data-scroll-target="#unidade-de-análise-e-critérios"><span class="header-section-number">F.13.1</span> Unidade de análise e critérios</a></li>
  <li><a href="#análise-temática-de-q14-maior-contribuição-da-ia" id="toc-análise-temática-de-q14-maior-contribuição-da-ia" class="nav-link" data-scroll-target="#análise-temática-de-q14-maior-contribuição-da-ia"><span class="header-section-number">F.13.2</span> Análise temática de Q14 — Maior contribuição da IA</a></li>
  <li><a href="#principais-dificuldades-e-sugestões-de-ajuste-q15" id="toc-principais-dificuldades-e-sugestões-de-ajuste-q15" class="nav-link" data-scroll-target="#principais-dificuldades-e-sugestões-de-ajuste-q15"><span class="header-section-number">F.13.3</span> Principais dificuldades e sugestões de ajuste — Q15</a></li>
  <li><a href="#síntese-da-análise-temática-de-q14-e-q15" id="toc-síntese-da-análise-temática-de-q14-e-q15" class="nav-link" data-scroll-target="#síntese-da-análise-temática-de-q14-e-q15"><span class="header-section-number">F.13.4</span> Síntese da Análise Temática de <code>Q14</code> e <code>Q15</code></a></li>
  <li><a href="#resultados-globais-por-resposta" id="toc-resultados-globais-por-resposta" class="nav-link" data-scroll-target="#resultados-globais-por-resposta"><span class="header-section-number">F.13.5</span> Resultados globais por resposta</a></li>
  <li><a href="#refinamento-da-valência-por-tema" id="toc-refinamento-da-valência-por-tema" class="nav-link" data-scroll-target="#refinamento-da-valência-por-tema"><span class="header-section-number">F.13.6</span> Refinamento da valência por tema</a></li>
  <li><a href="#observações-metodológicas" id="toc-observações-metodológicas" class="nav-link" data-scroll-target="#observações-metodológicas"><span class="header-section-number">F.13.7</span> Observações metodológicas</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../apendice_a_mctest.html">Apêndices</a></li><li class="breadcrumb-item"><a href="../apendice_f/apendice_f.html"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Análise de Percepção e Avaliação Didática: PDI-VC 2026.2</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="apendice-pdi-vc-2026-2" class="quarto-section-identifier">Apêndice F — Análise de Percepção e Avaliação Didática: PDI-VC 2026.2</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="https://colab.research.google.com/github/fzampirolli/pdi-vc/blob/master/notebooks_alunos/apendice_f/apendice_f_aluno.ipynb"><img src="imagens/colab-badge.png" class="img-fluid" style="width:16.0%"></a> <a href="https://github.com/fzampirolli/pdi-vc"><img src="imagens/github-badge.png" class="img-fluid" style="width:19.0%"></a></p>
<p>Este apêndice apresenta uma análise <strong>quantitativa e qualitativa, agregada e não identificável</strong>, da percepção dos estudantes sobre a experiência pedagógica na disciplina de <strong>Processamento Digital de Imagens e Visão Computacional (PDI-VC)</strong>, oferecida no segundo quadrimestre de 2026. A apresentação dos resultados foi estruturada de modo a preservar a <strong>confidencialidade e a não identificação dos participantes</strong>, não sendo divulgados nomes, endereços eletrônicos, respostas individualizadas ou quaisquer outros elementos que permitam a identificação direta ou indireta de estudantes.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Proteção da confidencialidade, tratamento dos dados e reprodutibilidade
</div>
</div>
<div class="callout-body-container callout-body">
<p>As análises apresentadas neste apêndice são realizadas exclusivamente sobre <strong>dados agregados ou anonimizados</strong>, utilizados para fins de avaliação e análise da experiência pedagógica. Os resultados são apresentados de forma coletiva, sem associação entre respostas e identidades individuais.</p>
<p>As tabelas, estatísticas e gráficos são gerados de forma <strong>automática e reprodutível</strong> a partir dos dados utilizados na análise. O <em>notebook Colab</em> disponibilizado pelo ícone no canto superior esquerdo documenta os procedimentos computacionais empregados, incluindo o processamento, a transformação e a geração dos resultados apresentados neste apêndice.</p>
<p>Os <strong>dados brutos contendo informações potencialmente identificáveis não são publicados</strong>, incorporados ao material de divulgação ou disponibilizados por meio do <em>notebook</em>. Da mesma forma, respostas individuais não são apresentadas de maneira que possibilite sua atribuição a participantes específicos. Eventuais materiais necessários à <strong>auditoria metodológica</strong> permanecem sob guarda do responsável pela pesquisa e poderão ser disponibilizados, quando cabível, exclusivamente em condições compatíveis com as exigências éticas aplicáveis e sem exposição de dados pessoais ou identificáveis.</p>
<p>A identificação utilizada exclusivamente para o pareamento entre os questionários PRÉ e PÓS, quando necessária à análise longitudinal, não é divulgada nos resultados. Após a realização dos procedimentos analíticos que dependem desse pareamento, os resultados são apresentados de forma agregada, preservando-se a confidencialidade dos participantes.</p>
</div>
</div>
<section id="caracterização-da-amostra-e-metodologia-de-coleta" class="level2" data-number="F.1">
<h2 data-number="F.1" class="anchored" data-anchor-id="caracterização-da-amostra-e-metodologia-de-coleta"><span class="header-section-number">F.1</span> Caracterização da Amostra e Metodologia de Coleta</h2>
<p>A coleta de dados ocorreu em dois momentos do quadrimestre. O <strong>questionário PRÉ-curso</strong>, aplicado na primeira semana de aula, caracterizou o perfil dos estudantes antes da intervenção pedagógica. O <strong>questionário PÓS-curso</strong>, aplicado ao final do quadrimestre, após a utilização dos recursos didáticos e das estratégias analisadas neste apêndice, avaliou a experiência na disciplina e foi aplicado juntamente com a prova final.</p>
<p>Foram obtidas <strong>104 respostas no PRÉ</strong> e <strong>80 no PÓS</strong>. Com base nas informações fornecidas pelos estudantes para possibilitar a identificação entre os dois momentos, foram identificados <strong>15 estudantes que responderam a ambos os questionários</strong>, constituindo a <strong>amostra pareada</strong> utilizada na análise da evolução individual.</p>
<p>A distribuição dos respondentes entre as três turmas é apresentada na <a href="#tbl-contagem-turmas" class="quarto-xref">Tabela&nbsp;<span>F.1</span></a>. As turmas <strong>DA1</strong> e <strong>DA2</strong> correspondem à graduação, oferecida no período <strong>matutino</strong>, enquanto a <strong>MCC</strong> corresponde à pós-graduação, oferecida no período <strong>vespertino</strong>. Entre o PRÉ e o PÓS, o número de respostas <strong>manteve-se em 39 na DA1</strong>, enquanto diminuiu de <strong>46 para 30 na DA2</strong> e de <strong>19 para 11 na MCC</strong>. Assim, a redução da amostra concentrou-se nas turmas <strong>DA2 e MCC</strong>, enquanto a participação da <strong>DA1 permaneceu estável</strong>.</p>
<p>Considerando a natureza ordinal das escalas <em>Likert</em> de cinco pontos, foram empregados <strong>testes estatísticos não paramétricos</strong>. O teste de <em>Mann–Whitney U</em> <span class="citation" data-cites="mann1947">(<a href="../referencias.html#ref-mann1947" role="doc-biblioref">Mann; Whitney, 1947</a>)</span> foi utilizado nas comparações entre amostras independentes; o teste de <em>Kruskal–Wallis</em> <span class="citation" data-cites="kruskal1952">(<a href="../referencias.html#ref-kruskal1952" role="doc-biblioref">Kruskal; Wallis, 1952</a>)</span>, nas comparações entre mais de dois grupos independentes; e o teste de Friedman <span class="citation" data-cites="friedman1937">(<a href="../referencias.html#ref-friedman1937" role="doc-biblioref">Friedman, 1937</a>)</span>, na comparação entre diferentes recursos avaliados pelos mesmos estudantes. Para a comparação pareada entre PRÉ e PÓS, empregou-se o teste de <em>Wilcoxon</em> <span class="citation" data-cites="wilcoxon1945">(<a href="../referencias.html#ref-wilcoxon1945" role="doc-biblioref">Wilcoxon, 1945</a>)</span>.</p>
<p>Como complemento aos testes de significância, foram analisados <strong>tamanhos de efeito</strong>, <strong>correlações de <em>Spearman</em></strong>, <strong>consistência interna pelo <span class="math inline">\(\alpha\)</span> de <em>Cronbach</em></strong> e <strong>preferências declaradas</strong>, permitindo uma interpretação mais ampla dos resultados.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Nota Metodológica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os testes estatísticos permitem identificar diferenças e associações, mas não estabelecem relações causais. Assim, diferenças entre recursos que utilizaram ou não IA não devem ser interpretadas isoladamente como efeito da tecnologia, uma vez que esses recursos apresentam finalidades, formatos, níveis de interação e momentos de utilização distintos.</p>
</div>
</div>
<div class="cell" data-quarto-raw="false" data-execution_count="3">
<div id="tbl-contagem-turmas" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3" data-quarto-raw="false">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-contagem-turmas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.1: Quantidade de respondentes por turma nos questionários PRÉ e PÓS.
</figcaption>
<div aria-describedby="tbl-contagem-turmas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Turma</th>
<th style="text-align: center;">PRÉ (n)</th>
<th style="text-align: center;">PÓS (n)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DA1</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">39</td>
</tr>
<tr class="even">
<td style="text-align: left;">DA2</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MCC</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: center;"><strong>104</strong></td>
<td style="text-align: center;"><strong>80</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="itens-do-questionário-pós" class="level2" data-number="F.2">
<h2 data-number="F.2" class="anchored" data-anchor-id="itens-do-questionário-pós"><span class="header-section-number">F.2</span> Itens do questionário PÓS</h2>
<p>O questionário PÓS foi estruturado em cinco blocos. O <strong>Bloco 1</strong> reúne a identificação opcional do estudante e a seleção de uma das três turmas. O <strong>Bloco 2</strong>, apresentado na <a href="#tbl-pos-bloco2" class="quarto-xref">Tabela&nbsp;<span>F.2</span></a>, aborda a <strong>autopercepção de aprendizado e desempenho</strong>. O <strong>Bloco 3</strong>, apresentado na <a href="#tbl-pos-bloco3" class="quarto-xref">Tabela&nbsp;<span>F.3</span></a> (<code>Q08</code>) e na <a href="#tbl-pos-q09" class="quarto-xref">Tabela&nbsp;<span>F.4</span></a> (<code>Q09</code>), avalia os <strong>recursos didáticos</strong>. O <strong>Bloco 4</strong>, apresentado na <a href="#tbl-pos-bloco4" class="quarto-xref">Tabela&nbsp;<span>F.5</span></a>, investiga a percepção sobre a <strong>integração da Inteligência Artificial (IA)</strong> ao processo de ensino e aprendizagem. Por fim, o <strong>Bloco 5</strong>, apresentado na <a href="#tbl-pos-bloco5" class="quarto-xref">Tabela&nbsp;<span>F.6</span></a>, reúne duas questões abertas.</p>
<p>Os itens avaliativos dos Blocos 2, 3 e 4 utilizam uma <strong>escala <em>Likert</em> de cinco pontos</strong>: 1 = <em>Discordo totalmente</em>; 2 = <em>Discordo</em>; 3 = <em>Indiferente</em>; 4 = <em>Concordo</em>; e 5 = <em>Concordo totalmente</em>. A questão <code>Q09</code>, pertencente ao Bloco 3, adota formato distinto, solicitando a <strong>seleção de exatamente quatro recursos</strong> considerados mais eficazes para a aprendizagem pelo estudante.</p>
<section id="itens-do-bloco-2-autopercepção-de-aprendizado-e-desempenho" class="level3" data-number="F.2.1">
<h3 data-number="F.2.1" class="anchored" data-anchor-id="itens-do-bloco-2-autopercepção-de-aprendizado-e-desempenho"><span class="header-section-number">F.2.1</span> Itens do Bloco 2 — Autopercepção de Aprendizado e Desempenho</h3>
<p>A <a href="#tbl-pos-bloco2" class="quarto-xref">Tabela&nbsp;<span>F.2</span></a> apresenta os sete itens do Bloco 2, que avaliam a <strong>autopercepção dos estudantes sobre o aprendizado e o desempenho</strong> ao final da disciplina. Os seis primeiros itens abrangem capacidade de programação, aplicação dos conhecimentos em outras disciplinas e na atuação profissional, fundamentos matemáticos, autonomia no uso de bibliotecas e percepção sobre o <em>feedback</em> por IA. Esses itens possuem correspondência com questões do questionário <strong>PRÉ</strong> e serão analisados de forma pareada na seção seguinte, permitindo avaliar a evolução das percepções individuais. O item <code>Q07</code> apresenta uma avaliação global da evolução dos conhecimentos teóricos e práticos em PDI-VC ao longo da disciplina.</p>
<div class="cell" data-tbl-colwidths="[8,80]" data-execution_count="4">
<div id="tbl-pos-bloco2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4" data-tbl-colwidths="[8,80]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pos-bloco2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.2: Itens do Bloco 2 — Autopercepção de Aprendizado e Desempenho.
</figcaption>
<div aria-describedby="tbl-pos-bloco2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Enunciado aplicado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q01</code></td>
<td style="text-align: left;"><strong>PÓS - Capacidade de Programação:</strong> Atualmente, consigo resolver problemas computacionais básicos usando programação.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q02</code></td>
<td style="text-align: left;"><strong>PÓS - Atuação Acadêmica:</strong> Os conhecimentos desenvolvidos nesta disciplina têm me ajudado na minha atuação acadêmica em outras disciplinas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q03</code></td>
<td style="text-align: left;"><strong>PÓS - Atuação Profissional:</strong> Os conhecimentos desenvolvidos nesta disciplina serão úteis para a minha atuação profissional</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q04</code></td>
<td style="text-align: left;"><strong>PÓS - Fundamentos Matemáticos:</strong> Atualmente, considero que minha base em Álgebra Linear e Cálculo (conceitos usados em PDI) é muito boa.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q05</code></td>
<td style="text-align: left;"><strong>PÓS - Autonomia com Bibliotecas:</strong> Atualmente, sinto que tenho boa autonomia para utilizar bibliotecas de processamento de dados/imagens (ex: OpenCV, NumPy, Matplotlib, morph.py).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q06</code></td>
<td style="text-align: left;"><strong>PÓS - Feedback por IA:</strong> Atualmente, considero útil o feedback automático de código gerado por IA.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q07</code></td>
<td style="text-align: left;"><strong>GLOBAL_BLOCO2 - Avaliação Geral do Aprendizado:</strong> De forma geral, considero que o meu nível de conhecimento teórico e prático na área de PDI-VC evoluiu significativamente ao longo desta disciplina.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="itens-do-bloco-3-recursos-didáticos" class="level3" data-number="F.2.2">
<h3 data-number="F.2.2" class="anchored" data-anchor-id="itens-do-bloco-3-recursos-didáticos"><span class="header-section-number">F.2.2</span> Itens do Bloco 3 — Recursos Didáticos</h3>
<p>O <strong>Bloco 3</strong> avalia os recursos didáticos utilizados na disciplina. É composto por dez itens de avaliação (<code>Q08_01</code>–<code>Q08_10</code>), apresentados na <a href="#tbl-pos-bloco3" class="quarto-xref">Tabela&nbsp;<span>F.3</span></a>; uma questão sobre o acesso ao VPL (<code>Q08_11</code>); uma questão de <strong>preferência pelos recursos</strong> (<code>Q09</code>); e uma <strong>avaliação global</strong> (<code>Q10</code>).</p>
<div class="cell" data-tbl-colwidths="[8,80]" data-execution_count="5">
<div id="tbl-pos-bloco3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5" data-tbl-colwidths="[8,80]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pos-bloco3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.3: Itens do Bloco 3 — Recursos Didáticos.
</figcaption>
<div aria-describedby="tbl-pos-bloco3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="5">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Enunciado aplicado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q08_01</code></td>
<td style="text-align: left;"><strong>Livro Interativo:</strong> O uso do Livro Interativo (HTML/IPYNB/PDF) com simuladores e teoria integrada contribuiu significativamente para o meu aprendizado.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_02</code></td>
<td style="text-align: left;"><strong>Material Didático por IA:</strong> Os vídeos curtos (~7 min) e os slides (~12 slides) produzidos via Gemini Notebook ajudaram a introduzir e sintetizar o conteúdo antes do início da aula prática no Colab</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_03</code></td>
<td style="text-align: left;"><strong>Simuladores Interativos:</strong> A manipulação visual de parâmetros em tempo real nos simuladores interativos (no HTML/Colab) facilitou a compreensão dos algoritmos.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_04</code></td>
<td style="text-align: left;"><strong>Resolução de EPs em Aula:</strong> A resolução acompanhada dos Exercícios de Programação (EPs) durante o horário de aula foi fundamental para o meu desempenho prático.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_05</code></td>
<td style="text-align: left;"><strong>Biblioteca morph.py:</strong> O uso da biblioteca didática morph.py (com implementações didáticas como mm.dil0 e otimizadas) tornou o código dos algoritmos mais transparente e compreensível.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_06</code></td>
<td style="text-align: left;"><strong>Provas e Simulados Paramétricos:</strong> As avaliações parametrizadas pelo MCTest e aplicadas via SEB (com questões individuais) foram eficazes para avaliar meu aprendizado de forma justa.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_07</code></td>
<td style="text-align: left;"><strong>Feedback Socrático no VPL:</strong> O feedback qualitativo/socrático gerado por IA ao pedir avaliação do código nos EPs do VPL/Moodle ajudou a identificar e corrigir erros na minha lógica.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_08</code></td>
<td style="text-align: left;"><strong>Rubrica por IA em Simulados/Provas:</strong> O relatório enviado por e-mail com a rubrica detalhada por IA e o resumo comparativo agregou valor ao meu processo de revisão das provas e simulados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_09</code></td>
<td style="text-align: left;"><strong>Correção Objetiva VPL:</strong> A validação automática objetiva por casos de teste no VPL/Moodle deu um retorno rápido e claro sobre o funcionamento do código.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_10</code></td>
<td style="text-align: left;"><strong>Uso do TestSuite.py:</strong> O testsuite.py facilitou testar meus EPs no Colab antes de submeter no VPL.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_11</code></td>
<td style="text-align: left;"><strong>VPL só na UFABC:</strong> O bloqueio de acesso ao VPL fora da rede da UFABC dificultou meus estudos.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q09</code></td>
<td style="text-align: left;"><strong>Ranking de Preferência:</strong> Escolha até 4 recursos que considerou MAIS EFICAZES no seu processo de estudo:</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q10</code></td>
<td style="text-align: left;"><strong>GLOBAL_BLOCO3 - Avaliação Geral dos Recursos Didáticos:</strong> Em conjunto, o ecossistema de recursos metodológicos oferecidos nesta disciplina (livro interativo, materiais multimídia por IA, simuladores, biblioteca didática e avaliações) foi altamente eficaz para o meu aprendizado.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A questão <code>Q09</code> utilizou um formato de <strong>seleção de preferência</strong>, no qual cada estudante deveria selecionar <strong>exatamente quatro recursos</strong> considerados mais eficazes para seu processo de estudo. A questão apresentou <strong>dez opções de recursos</strong>, relacionadas na <a href="#tbl-pos-q09" class="quarto-xref">Tabela&nbsp;<span>F.4</span></a>.</p>
<div class="cell" data-tbl-colwidths="[8,80]" data-execution_count="6">
<div id="tbl-pos-q09" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6" data-tbl-colwidths="[8,80]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pos-q09-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.4: Opções apresentadas na questão <code>Q09</code> — <em>Ranking</em> agregado por frequência de seleção.
</figcaption>
<div aria-describedby="tbl-pos-q09-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Recurso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q09_01</code></td>
<td style="text-align: left;"><strong>Gemini Audio/Visual:</strong> Material didático audiovisual gerado por IA (Vídeos e Slides do Gemini Notebook)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q09_02</code></td>
<td style="text-align: left;"><strong>Simuladores:</strong> Simuladores interativos (manipulação de parâmetros)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q09_03</code></td>
<td style="text-align: left;"><strong>EPs em Aula:</strong> Resolução dos Exercícios de Programação (EPs) em sala de aula</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q09_04</code></td>
<td style="text-align: left;"><strong>Livro Interativo:</strong> Livro interativo no formato HTML / Colab</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q09_05</code></td>
<td style="text-align: left;"><strong>morph.py:</strong> Biblioteca didática morph.py</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q09_06</code></td>
<td style="text-align: left;"><strong>IA Feedback VPL:</strong> Feedback socrático por IA a cada submissão de código no VPL/Moodle</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q09_07</code></td>
<td style="text-align: left;"><strong>IA Rubrica Provas:</strong> Feedback por e-mail com rubrica de avaliação qualitativa gerada por IA nos Simulados/Provas</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q09_08</code></td>
<td style="text-align: left;"><strong>SEB Simulados:</strong> Simulados quinzenais em laboratório (SEB)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q09_09</code></td>
<td style="text-align: left;"><strong>VPL Casos Teste:</strong> Validação objetiva por casos de teste no VPL</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q09_10</code></td>
<td style="text-align: left;"><strong>TestSuite.py:</strong> Uso do testsuite.py no Colab para testar EPs localmente</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="itens-do-bloco-4-avaliação-específica-do-uso-transversal-da-inteligência-artificial" class="level3" data-number="F.2.3">
<h3 data-number="F.2.3" class="anchored" data-anchor-id="itens-do-bloco-4-avaliação-específica-do-uso-transversal-da-inteligência-artificial"><span class="header-section-number">F.2.3</span> Itens do Bloco 4 — Avaliação Específica do Uso Transversal da Inteligência Artificial</h3>
<p>Os itens <code>Q11</code>–<code>Q13</code>, apresentados na <a href="#tbl-pos-bloco4" class="quarto-xref">Tabela&nbsp;<span>F.5</span></a>, avaliam a percepção dos estudantes sobre a <strong>integração transversal da Inteligência Artificial (IA)</strong> no processo de ensino e aprendizagem. Como utilizam a mesma escala <em>Likert</em> de cinco pontos descrita anteriormente, esses itens compõem, juntamente com os demais itens ordinais, a síntese dos <strong>21 itens <em>Likert</em></strong> apresentada ao final deste apêndice.</p>
<p>O item <code>Q08_11</code> e a questão <code>Q09</code>, pertencentes ao <strong>Bloco 3</strong>, não integram essa síntese, pois apresentam formatos e finalidades distintos da avaliação ordinal dos recursos didáticos. O <code>Q08_11</code> investiga uma dificuldade específica relacionada ao acesso ao VPL, enquanto <code>Q09</code> utiliza <strong>seleção de exatamente quatro recursos</strong>, sem estabelecer ordenação entre as alternativas.</p>
<div class="cell" data-tbl-colwidths="[8,80]" data-execution_count="7">
<div id="tbl-pos-bloco4" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7" data-tbl-colwidths="[8,80]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pos-bloco4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.5: Itens do Bloco 4 — Avaliação Específica do Uso Transversal da Inteligência Artificial
</figcaption>
<div aria-describedby="tbl-pos-bloco4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Enunciado aplicado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q11</code></td>
<td style="text-align: left;"><strong>Pensamento Crítico e Alucinações:</strong> Perceber eventuais limitações ou imprecisões nas explicações da IA (no feedback ou materiais) estimulou meu senso crítico sobre a correção do código.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q12</code></td>
<td style="text-align: left;"><strong>Transversalidade Pedagógica:</strong> Recomendo que essa abordagem integrada de IA (produção de material + feedback socrático no VPL + rubrica qualitativa em provas) seja adotada em outras disciplinas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q13</code></td>
<td style="text-align: left;"><strong>GLOBAL_BLOCO4 - Avaliação Geral da Integração de IA:</strong> O uso transversal e transparente de Inteligência Artificial ao longo da disciplina agregou valor significativo à minha experiência de aprendizado.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="bloco-5-questões-abertas" class="level3" data-number="F.2.4">
<h3 data-number="F.2.4" class="anchored" data-anchor-id="bloco-5-questões-abertas"><span class="header-section-number">F.2.4</span> Bloco 5 — Questões Abertas</h3>
<p>O <strong>Bloco 5</strong> reúne duas questões abertas e opcionais, apresentadas na <a href="#tbl-pos-bloco5" class="quarto-xref">Tabela&nbsp;<span>F.6</span></a>, destinadas a complementar a avaliação quantitativa com <em>feedback</em> qualitativo sobre a experiência dos estudantes com a metodologia da disciplina e, especificamente, sobre o uso da <strong>Inteligência Artificial (IA)</strong> no processo de ensino e aprendizagem.</p>
<div class="cell" data-tbl-colwidths="[8,80]" data-execution_count="8">
<div id="tbl-pos-bloco5" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8" data-tbl-colwidths="[8,80]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pos-bloco5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.6: Itens do Bloco 5 — Questões Abertas.
</figcaption>
<div aria-describedby="tbl-pos-bloco5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="8">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Enunciado aplicado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q14</code></td>
<td style="text-align: left;"><strong>Maior contribuição da IA:</strong> Dentre os usos da IA nesta disciplina (geração de material, feedback socrático nos EPs, rubrica nos simulados/provas), qual trouxe o maior ganho para o seu aprendizado? Por quê?</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q15</code></td>
<td style="text-align: left;"><strong>Dificuldades e ajustes metodológicos:</strong> Qual elemento da metodologia (SEB, MCTest, tempo de prova, feedback por IA, biblioteca) apresentou maior dificuldade ou precisará de ajustes nas próximas ofertas?</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As questões <code>Q14</code> e <code>Q15</code> não utilizaram escala ordinal nem alternativas predefinidas. As respostas, de caráter <strong>aberto e opcional</strong>, permitiram aos estudantes registrar livremente suas percepções, justificativas, dificuldades e sugestões de melhoria. Por esse motivo, esses itens não integram as análises estatísticas baseadas nas questões <em>Likert</em> e são examinados separadamente por meio de <strong>codificação temática</strong> e <strong>classificação de valência</strong>, apresentadas nas seções seguintes.</p>
</section>
</section>
<section id="perfil-acadêmico-dos-participantes" class="level2" data-number="F.3">
<h2 data-number="F.3" class="anchored" data-anchor-id="perfil-acadêmico-dos-participantes"><span class="header-section-number">F.3</span> Perfil acadêmico dos participantes</h2>
<p>A interpretação dos resultados deve considerar o <strong>perfil acadêmico dos participantes</strong>, especialmente a composição da amostra de graduação, formada majoritariamente por estudantes em <strong>etapas avançadas da formação</strong>. No questionário PRÉ, <strong>88 estudantes indicaram Ciência da Computação</strong> e <strong>30, Ciência de Dados</strong> como cursos que estavam cursando ou pretendiam cursar após o Bacharelado Interdisciplinar. Como era permitida a seleção de mais de uma opção, esses quantitativos não são mutuamente exclusivos, conforme apresentado na <a href="#tbl-formacao-graduacao" class="quarto-xref">Tabela&nbsp;<span>F.7</span></a>.</p>
<p>Essa composição ajuda a contextualizar a elevada autopercepção de <strong>capacidade de programação</strong> (<code>Q01</code>) observada no PRÉ e no PÓS, analisada nas subseções seguintes. Por outro lado, <strong>Processamento Digital de Imagens (PDI) não constitui componente obrigatório da matriz curricular de todos esses cursos</strong>; portanto, a formação acadêmica não permite presumir experiência prévia específica nessa área.</p>
<p>Na <strong>pós-graduação</strong>, observa-se maior diversidade nas formações de origem, incluindo Física, Engenharia Biomédica, Matemática, Ciências Atuariais, Biotecnologia, Computação e Ciência de Dados. Essa heterogeneidade corresponde a trajetórias acadêmicas distintas e pode estar associada a diferentes níveis de experiência prévia em programação e processamento de imagens.</p>
<p>Assim, a elevada autopercepção de <strong>capacidade de programação</strong> no PRÉ (ver <a href="#tbl-pre-pos-wilcoxon" class="quarto-xref">Tabela&nbsp;<span>F.8</span></a>) deve ser interpretada considerando a composição da amostra. A concentração de estudantes de graduação em etapas avançadas da formação pode ter contribuído para um possível <strong>efeito teto</strong> em <code>Q01</code>, cuja percepção já era elevada no início da disciplina e permaneceu em nível alto nos dois momentos.</p>
<div class="cell" data-execution_count="9">
<div id="tbl-formacao-graduacao" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-formacao-graduacao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.7: Cursos indicados pelos estudantes de graduação. Percentuais calculados sobre os 104 respondentes. Como a questão permitia múltiplas respostas, os percentuais não são mutuamente exclusivos e podem somar mais de 100%.
</figcaption>
<div aria-describedby="tbl-formacao-graduacao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 86%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Curso/área indicada</th>
<th style="text-align: center;">Estudantes (n)</th>
<th style="text-align: center;">Percentual*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ciência da Computação</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">84,6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ciência de Dados</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">28,8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instrumentação</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">7,7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Automação e Robótica</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">7,7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matemática</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">5,8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Informação</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">5,8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biomédica</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4,8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Física</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3,8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Neurociência</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2,9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gestão</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1,9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outros (1 estudante cada): Aeroespacial, Ambiental e Urbana, Biotecnologia, Ciências Atuariais, Ciências Biológicas, Ciências atuariais, Energia, Filosofia, Pós em Ciência da Computação, formado em 1997</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">1,0% cada</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="sec-pre-pos" class="level2" data-number="F.4">
<h2 data-number="F.4" class="anchored" data-anchor-id="sec-pre-pos"><span class="header-section-number">F.4</span> Comparação entre os Questionários PRÉ e PÓS</h2>
<p>A comparação entre os questionários <strong>PRÉ</strong> e <strong>PÓS</strong> busca identificar mudanças nas percepções dos estudantes ao longo da disciplina. A análise contempla seis dimensões: capacidade de programação, <em>feedback</em> por IA, atuação acadêmica, atuação profissional, fundamentos matemáticos e autonomia no uso de bibliotecas.</p>
<p>Para avaliar essas dimensões, foram empregados dois procedimentos complementares. O teste de <em>Wilcoxon</em> foi aplicado aos <strong>15 estudantes pareados</strong>, permitindo avaliar mudanças nas percepções individuais. O teste de <em>Mann–Whitney U</em> foi aplicado às <strong>amostras completas</strong>, permitindo verificar diferenças na distribuição das respostas entre os dois momentos. Dessa forma, o primeiro procedimento avalia <strong>mudanças intraindividuais</strong>, enquanto o segundo identifica <strong>diferenças entre as amostras</strong>, cuja composição não é necessariamente a mesma.</p>
<section id="evolução-da-percepção-dos-estudantes-pré-versus-pós" class="level3" data-number="F.4.1">
<h3 data-number="F.4.1" class="anchored" data-anchor-id="evolução-da-percepção-dos-estudantes-pré-versus-pós"><span class="header-section-number">F.4.1</span> Evolução da Percepção dos Estudantes: PRÉ versus PÓS</h3>
<p>A comparação entre os questionários <strong>PRÉ</strong> e <strong>PÓS</strong> busca identificar mudanças nas percepções dos estudantes ao longo da disciplina. Foram obtidas <strong>104 respostas no PRÉ</strong> e <strong>80 no PÓS</strong>, com <strong>15 estudantes identificados nos dois momentos</strong>, constituindo a amostra pareada utilizada na análise da evolução individual.</p>
<p>A análise contempla seis dimensões:</p>
<ul>
<li><strong>Capacidade de programação</strong> (<code>PRE_Q01 → Q01</code>);</li>
<li><strong><em>Feedback</em> por IA</strong> (<code>PRE_Q02 → Q06</code>);</li>
<li><strong>Atuação acadêmica</strong> (<code>PRE_Q03 → Q02</code>);</li>
<li><strong>Atuação profissional</strong> (<code>PRE_Q04 → Q03</code>);</li>
<li><strong>Fundamentos matemáticos</strong> (<code>PRE_Q05 → Q04</code>);</li>
<li><strong>Autonomia com bibliotecas</strong> (<code>PRE_Q06 → Q05</code>).</li>
</ul>
<p>As médias e medianas apresentadas na <a href="#tbl-pre-pos-wilcoxon" class="quarto-xref">Tabela&nbsp;<span>F.8</span></a> referem-se às <strong>amostras completas</strong> (PRÉ <span class="math inline">\(N=104\)</span>; PÓS <span class="math inline">\(N=80\)</span>) e têm finalidade exclusivamente descritiva, correspondendo aos mesmos valores apresentados na <a href="#tbl-pre-pos-mw" class="quarto-xref">Tabela&nbsp;<span>F.9</span></a>. A evolução individual foi avaliada pelo teste de <em>Wilcoxon</em>, aplicado aos <strong>15 estudantes pareados</strong>. Como esse teste é baseado nas diferenças ordenadas entre as observações, a <strong>mediana</strong> é apresentada juntamente com a média, permitindo uma interpretação mais adequada da tendência central em conjunto com o resultado inferencial.</p>
<div class="cell" data-execution_count="10">
<div id="tbl-pre-pos-wilcoxon" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pre-pos-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.8: Comparação descritiva (média e mediana) das amostras completas e teste de Wilcoxon para a amostra pareada de 15 estudantes.
</figcaption>
<div aria-describedby="tbl-pre-pos-wilcoxon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 19%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: center;">Média PRÉ (N=104)</th>
<th style="text-align: center;">Média PÓS (N=80)</th>
<th style="text-align: center;">Mediana PRÉ</th>
<th style="text-align: center;">Mediana PÓS</th>
<th style="text-align: center;">p Wilcoxon (pareado, n=15)</th>
<th style="text-align: center;">Interpretação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Capacidade de programação</td>
<td style="text-align: center;">4,481</td>
<td style="text-align: center;">4,562</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0,655</td>
<td style="text-align: center;">Sem evidência de mudança</td>
</tr>
<tr class="even">
<td style="text-align: left;">Feedback por IA</td>
<td style="text-align: center;">3,981</td>
<td style="text-align: center;">3,438</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,070</td>
<td style="text-align: center;">Sem evidência de mudança</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Atuação acadêmica</td>
<td style="text-align: center;">4,385</td>
<td style="text-align: center;">3,712</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,083</td>
<td style="text-align: center;">Sem evidência de mudança</td>
</tr>
<tr class="even">
<td style="text-align: left;">Atuação profissional</td>
<td style="text-align: center;">4,356</td>
<td style="text-align: center;">3,725</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,052</td>
<td style="text-align: center;">Sem evidência de mudança</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fundamentos matemáticos</td>
<td style="text-align: center;">3,212</td>
<td style="text-align: center;">3,538</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,272</td>
<td style="text-align: center;">Sem evidência de mudança</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autonomia com bibliotecas</td>
<td style="text-align: center;">3,663</td>
<td style="text-align: center;">3,825</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,885</td>
<td style="text-align: center;">Sem evidência de mudança</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Os resultados do teste de <em>Wilcoxon</em> <strong>não forneceram evidência estatisticamente significativa de mudança sistemática</strong> entre PRÉ e PÓS em nenhuma das seis dimensões (<span class="math inline">\(p&gt;0,05\)</span>). Essa ausência de significância não demonstra que não tenha ocorrido mudança; indica apenas que, na <strong>amostra pareada de 15 estudantes</strong>, não foi obtida evidência estatística suficiente para detectá-la.</p>
<p>A <strong>capacidade de programação</strong> apresentou médias elevadas nos dois momentos, passando de <strong>4,481 para 4,562</strong>, com mediana igual a 5 em ambos. O teste pareado (<span class="math inline">\(p=0,655\)</span>) não indicou evidência de mudança sistemática, resultado compatível com a elevada percepção inicial observada para essa dimensão.</p>
<p>O <strong><em>feedback</em> por IA</strong> apresentou redução descritiva da média, de <strong>3,981 para 3,438</strong>, embora a diferença não tenha sido estatisticamente significativa (<span class="math inline">\(p=0,070\)</span>). Também foram observadas reduções em <strong>atuação acadêmica</strong>, de 4,385 para 3,712 (<span class="math inline">\(p=0,083\)</span>), e <strong>atuação profissional</strong>, de 4,356 para 3,725 (<span class="math inline">\(p=0,052\)</span>). Apesar das variações descritivas, os resultados não permitem afirmar que tenha ocorrido mudança sistemática nessas dimensões.</p>
<p>Em sentido oposto, <strong>fundamentos matemáticos</strong> apresentou aumento da média, de <strong>3,212 para 3,538</strong> (<span class="math inline">\(p=0,272\)</span>), enquanto a <strong>autonomia com bibliotecas</strong> passou de <strong>3,663 para 3,825</strong> (<span class="math inline">\(p=0,885\)</span>). Novamente, as diferenças observadas não alcançaram significância estatística.</p>
<p>As reduções descritivas em <strong>atuação acadêmica</strong> e <strong>atuação profissional</strong> podem ser compatíveis com uma possível <strong>recalibração das expectativas e da autoavaliação</strong>, à medida que os estudantes entram em contato com problemas concretos de PDI-VC. Essa interpretação deve, contudo, ser considerada apenas uma <strong>hipótese pedagógica</strong>, e não uma conclusão causal derivada dos resultados estatísticos.</p>
</section>
<section id="análise-complementar-entre-as-amostras-completas" class="level3" data-number="F.4.2">
<h3 data-number="F.4.2" class="anchored" data-anchor-id="análise-complementar-entre-as-amostras-completas"><span class="header-section-number">F.4.2</span> Análise complementar entre as amostras completas</h3>
<p>Como análise complementar, o teste de <em>Mann–Whitney U</em> foi aplicado às <strong>amostras completas</strong> do PRÉ (<span class="math inline">\(N=104\)</span>) e do PÓS (<span class="math inline">\(N=80\)</span>), sem considerar o pareamento entre indivíduos. Os resultados são apresentados na <a href="#tbl-pre-pos-mw" class="quarto-xref">Tabela&nbsp;<span>F.9</span></a> e permitem verificar se as distribuições das respostas diferem entre os dois momentos, independentemente da correspondência individual entre os participantes.</p>
<div class="cell" data-execution_count="11">
<div id="tbl-pre-pos-mw" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="11">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pre-pos-mw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.9: Comparação entre as amostras completas PRÉ (N=104) e PÓS (N=80) pelo teste de Mann-Whitney U. O d de Cohen é apresentado como medida padronizada da diferença entre as médias, enquanto a significância estatística foi avaliada pelo teste de Mann-Whitney U.
</figcaption>
<div aria-describedby="tbl-pre-pos-mw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="11">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: center;">Média PRÉ</th>
<th style="text-align: center;">Média PÓS</th>
<th style="text-align: center;">Mediana PRÉ</th>
<th style="text-align: center;">Mediana PÓS</th>
<th style="text-align: center;">d de Cohen</th>
<th style="text-align: center;">p-valor</th>
<th style="text-align: center;">Efeito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Atuação acadêmica</td>
<td style="text-align: center;">4,385</td>
<td style="text-align: center;">3,712</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">-0,775</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Médio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Atuação profissional</td>
<td style="text-align: center;">4,356</td>
<td style="text-align: center;">3,725</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">-0,677</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Médio</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Feedback por IA</td>
<td style="text-align: center;">3,981</td>
<td style="text-align: center;">3,438</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">-0,471</td>
<td style="text-align: center;">0,008</td>
<td style="text-align: center;">Pequeno</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fundamentos matemáticos</td>
<td style="text-align: center;">3,212</td>
<td style="text-align: center;">3,538</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,303</td>
<td style="text-align: center;">0,048</td>
<td style="text-align: center;">Pequeno</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capacidade de programação</td>
<td style="text-align: center;">4,481</td>
<td style="text-align: center;">4,562</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0,108</td>
<td style="text-align: center;">0,301</td>
<td style="text-align: center;">Muito pequeno</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autonomia com bibliotecas</td>
<td style="text-align: center;">3,663</td>
<td style="text-align: center;">3,825</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,142</td>
<td style="text-align: center;">0,865</td>
<td style="text-align: center;">Muito pequeno</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Para a interpretação do <span class="math inline">\(d\)</span> de <em>Cohen</em>, foram adotados, de forma aproximada, os seguintes intervalos: valores absolutos inferiores a 0,20 foram classificados como <strong>muito pequenos</strong>; entre 0,20 e 0,49, como <strong>pequenos</strong>; entre 0,50 e 0,79, como <strong>médios</strong>; e iguais ou superiores a 0,80, como <strong>grandes</strong>.</p>
<p>A comparação entre as amostras completas identificou diferenças estatisticamente significativas em <strong>atuação acadêmica</strong> (<span class="math inline">\(p&lt;0,001\)</span>), <strong>atuação profissional</strong> (<span class="math inline">\(p&lt;0,001\)</span>), <strong><em>feedback</em> por IA</strong> (<span class="math inline">\(p=0,008\)</span>) e <strong>fundamentos matemáticos</strong> (<span class="math inline">\(p=0,048\)</span>). Os maiores tamanhos de efeito foram observados em atuação acadêmica (<span class="math inline">\(d=-0,775\)</span>) e atuação profissional (<span class="math inline">\(d=-0,677\)</span>), ambos classificados como <strong>médios</strong>. Em <em>feedback</em> por IA, o efeito foi <strong>pequeno</strong> (<span class="math inline">\(d=-0,471\)</span>), assim como em fundamentos matemáticos (<span class="math inline">\(d=0,303\)</span>).</p>
<p>Em contraste, <strong>capacidade de programação</strong> (<span class="math inline">\(d=0,108\)</span>; <span class="math inline">\(p=0,301\)</span>) e <strong>autonomia com bibliotecas</strong> (<span class="math inline">\(d=0,142\)</span>; <span class="math inline">\(p=0,865\)</span>) não apresentaram diferenças estatisticamente significativas, com efeitos <strong>muito pequenos</strong>.</p>
<p>Esses resultados <strong>não devem ser interpretados como evidência de evolução individual</strong>, pois o teste de <em>Mann–Whitney U</em> compara amostras independentes. As diferenças observadas podem decorrer tanto de mudanças entre os momentos quanto da composição distinta dos respondentes. Assim, os resultados caracterizam <strong>diferenças entre os conjuntos de participantes do PRÉ e do PÓS</strong>, e não efeitos atribuíveis à disciplina. Para avaliar mudanças intraindividuais, devem ser considerados os resultados do teste de <em>Wilcoxon</em> aplicado aos <strong>15 estudantes pareados</strong>.</p>
</section>
</section>
<section id="avaliação-dos-recursos-didáticos-no-pós-teste-de-friedman" class="level2" data-number="F.5">
<h2 data-number="F.5" class="anchored" data-anchor-id="avaliação-dos-recursos-didáticos-no-pós-teste-de-friedman"><span class="header-section-number">F.5</span> Avaliação dos Recursos Didáticos no PÓS — Teste de Friedman</h2>
<p>O Bloco 3 do questionário PÓS avalia <strong>dez recursos didáticos</strong> utilizados durante a disciplina, correspondentes aos itens <code>Q08_01</code>–<code>Q08_10</code>, apresentados na <a href="#tbl-bloco3-friedman" class="quarto-xref">Tabela&nbsp;<span>F.10</span></a> e ordenados pela média. Os recursos contemplam diferentes estratégias pedagógicas, com distintos níveis de participação da IA: alguns não a utilizaram diretamente; outros a empregaram como ferramenta de apoio; e três a utilizaram diretamente na <strong>geração de conteúdo, <em>feedback</em> ou rubricas</strong>.</p>
<p>Foram considerados <strong>80 estudantes</strong>, cada um avaliando os dez recursos. O teste de Friedman <span class="citation" data-cites="friedman1937">(<a href="../referencias.html#ref-friedman1937" role="doc-biblioref">Friedman, 1937</a>)</span> indicou <strong>diferença estatisticamente significativa</strong> entre as avaliações, <span class="math inline">\(\chi^2(9)=189,662\)</span>, <span class="math inline">\(p&lt;0,001\)</span>, rejeitando a hipótese de avaliações equivalentes para todos os recursos. Portanto, os estudantes <strong>diferenciaram os recursos quanto à sua avaliação</strong>.</p>
<p>O <strong>W de Kendall</strong> <span class="citation" data-cites="kendall1945">(<a href="../referencias.html#ref-kendall1945" role="doc-biblioref">Kendall, 1945</a>)</span> foi <span class="math inline">\(W=0,263\)</span>, indicando <strong>concordância baixa a moderada</strong> entre os estudantes quanto à ordenação dos recursos. Assim, embora as avaliações apresentem diferenças estatisticamente significativas, há apenas concordância limitada sobre a hierarquia de preferência entre os dez recursos.</p>
<div class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Friedman: N=80, chi2(9)=189.662, p=4.85e-36
W de Kendall: 0.263</code></pre>
</div>
<div id="tbl-bloco3-friedman" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="12">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bloco3-friedman-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.10: <em>Ranking</em> médio dos dez recursos didáticos avaliados no Bloco 3 (Q08_01–Q08_10), ordenado da avaliação mais alta para a mais baixa.
</figcaption>
<div aria-describedby="tbl-bloco3-friedman-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="12">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 45%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Recurso</th>
<th style="text-align: center;">Média</th>
<th style="text-align: center;">Mediana</th>
<th style="text-align: center;">Rank médio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q08_04</code></td>
<td style="text-align: left;">Resolução de EPs em Aula</td>
<td style="text-align: center;">4,588</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4,088</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_05</code></td>
<td style="text-align: left;">Biblioteca morph.py</td>
<td style="text-align: center;">4,300</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4,550</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_03</code></td>
<td style="text-align: left;">Simuladores Interativos</td>
<td style="text-align: center;">4,362</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4,600</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_09</code></td>
<td style="text-align: left;">Correção Objetiva VPL</td>
<td style="text-align: center;">4,213</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4,888</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_01</code></td>
<td style="text-align: left;">Livro Interativo</td>
<td style="text-align: center;">4,287</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4,900</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_10</code></td>
<td style="text-align: left;">Uso do TestSuite.py</td>
<td style="text-align: center;">4,263</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4,906</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_06</code></td>
<td style="text-align: left;">Provas e Simulados Paramétricos</td>
<td style="text-align: center;">4,075</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5,438</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_08</code></td>
<td style="text-align: left;">Rubrica por IA em Simulados/Provas</td>
<td style="text-align: center;">3,587</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">6,719</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q08_07</code></td>
<td style="text-align: left;">Feedback Socrático no VPL</td>
<td style="text-align: center;">3,388</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">7,162</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q08_02</code></td>
<td style="text-align: left;">Material Didático por IA</td>
<td style="text-align: center;">3,087</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7,750</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="classificação-dos-recursos-segundo-o-papel-da-ia" class="level3" data-number="F.5.1">
<h3 data-number="F.5.1" class="anchored" data-anchor-id="classificação-dos-recursos-segundo-o-papel-da-ia"><span class="header-section-number">F.5.1</span> Classificação dos recursos segundo o papel da IA</h3>
<p>Para interpretar os resultados de forma adequada, os dez recursos avaliados em <code>Q08</code> são classificados em três grupos, conforme apresentado na <a href="#tbl-classificacao-ia" class="quarto-xref">Tabela&nbsp;<span>F.11</span></a>.</p>
<p>A classificação considera o <strong>papel da IA na produção, preparação ou funcionamento dos recursos</strong>, e não apenas a interação direta do estudante com a tecnologia. Dessa forma, distingue-se o uso da IA como ferramenta de <strong>apoio à programação, preparação ou implementação</strong> de sua participação direta na <strong>geração de conteúdo didático, <em>feedback</em> ou rubricas</strong>. Essa distinção é importante para evitar que recursos com diferentes níveis e finalidades de uso da IA sejam interpretados como pertencentes a uma única categoria tecnológica.</p>
<div class="cell" data-execution_count="13">
<div id="tbl-classificacao-ia" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="13">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classificacao-ia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.11: Classificação dos dez recursos didáticos segundo o papel da Inteligência Artificial.
</figcaption>
<div aria-describedby="tbl-classificacao-ia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="13">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 67%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: left;">Recursos</th>
<th style="text-align: left;">Participação da IA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Sem uso direto de IA</strong></td>
<td style="text-align: left;"><code>Q08_04</code> — Resolução de EPs em Aula; <code>Q08_09</code> — Correção Objetiva VPL</td>
<td style="text-align: left;">A IA não participa diretamente do recurso</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>IA como ferramenta de apoio</strong></td>
<td style="text-align: left;"><code>Q08_01</code> — Livro Interativo; <code>Q08_03</code> — Simuladores Interativos; <code>Q08_05</code> — Biblioteca morph.py; <code>Q08_06</code> — Provas e Simulados Paramétricos; <code>Q08_10</code> — Uso do TestSuite.py</td>
<td style="text-align: left;">Apoio à programação, preparação ou formatação</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>IA com participação direta</strong></td>
<td style="text-align: left;"><code>Q08_02</code> — Material Didático por IA; <code>Q08_07</code> — Feedback Socrático no VPL; <code>Q08_08</code> — Rubrica por IA em Simulados/Provas</td>
<td style="text-align: left;">Geração direta de conteúdo, feedback ou rubrica</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="ranking-agregado-por-frequência-de-seleção-dos-recursos" class="level3" data-number="F.5.2">
<h3 data-number="F.5.2" class="anchored" data-anchor-id="ranking-agregado-por-frequência-de-seleção-dos-recursos"><span class="header-section-number">F.5.2</span> <em>Ranking</em> agregado por frequência de seleção dos recursos</h3>
<p>A <a href="#tbl-q08-ranking" class="quarto-xref">Tabela&nbsp;<span>F.12</span></a> apresenta a ordenação dos dez recursos segundo a média das avaliações em <code>Q08</code>, acompanhada do desvio-padrão, da mediana e do teste de diferença em relação ao valor neutro de 3,0.</p>
<div class="cell" data-execution_count="14">
<div id="tbl-q08-ranking" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="14">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-q08-ranking-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.12: Avaliação dos dez recursos didáticos no questionário PÓS, ordenada pela média. O p-valor refere-se ao teste de postos sinalizados de Wilcoxon para uma amostra, tendo 3,0 como valor de referência.
</figcaption>
<div aria-describedby="tbl-q08-ranking-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="14">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 37%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Posição</th>
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Recurso</th>
<th style="text-align: center;">Média</th>
<th style="text-align: center;">DP</th>
<th style="text-align: center;">Mediana</th>
<th style="text-align: center;">p vs.&nbsp;3,0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;"><code>Q08_04</code></td>
<td style="text-align: left;">Resolução de EPs em Aula</td>
<td style="text-align: center;">4,588</td>
<td style="text-align: center;">0,650</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;"><code>Q08_03</code></td>
<td style="text-align: left;">Simuladores Interativos</td>
<td style="text-align: center;">4,362</td>
<td style="text-align: center;">0,846</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;"><code>Q08_05</code></td>
<td style="text-align: left;">Biblioteca morph.py</td>
<td style="text-align: center;">4,300</td>
<td style="text-align: center;">1,048</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;"><code>Q08_01</code></td>
<td style="text-align: left;">Livro Interativo</td>
<td style="text-align: center;">4,287</td>
<td style="text-align: center;">0,814</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;"><code>Q08_10</code></td>
<td style="text-align: left;">Uso do TestSuite.py</td>
<td style="text-align: center;">4,263</td>
<td style="text-align: center;">0,938</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;"><code>Q08_09</code></td>
<td style="text-align: left;">Correção Objetiva VPL</td>
<td style="text-align: center;">4,213</td>
<td style="text-align: center;">1,015</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;"><code>Q08_06</code></td>
<td style="text-align: left;">Provas e Simulados Paramétricos</td>
<td style="text-align: center;">4,075</td>
<td style="text-align: center;">1,077</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: left;"><code>Q08_08</code></td>
<td style="text-align: left;">Rubrica por IA em Simulados/Provas</td>
<td style="text-align: center;">3,587</td>
<td style="text-align: center;">1,099</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: left;"><code>Q08_07</code></td>
<td style="text-align: left;">Feedback Socrático no VPL</td>
<td style="text-align: center;">3,388</td>
<td style="text-align: center;">1,248</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,011</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: left;"><code>Q08_02</code></td>
<td style="text-align: left;">Material Didático por IA</td>
<td style="text-align: center;">3,087</td>
<td style="text-align: center;">1,361</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0,710</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Os <strong>sete primeiros recursos</strong> apresentaram médias superiores a 4,0 e avaliações significativamente acima do ponto neutro (<span class="math inline">\(p&lt;0,001\)</span>). A <strong>Resolução de EPs em Aula</strong> obteve a maior média (4,588), seguida pelos <strong>Simuladores Interativos</strong> (4,362) e pela <strong>Biblioteca <code>morph.py</code></strong> (4,300). Também apresentaram avaliações elevadas o <strong>Livro Interativo</strong> (4,287), o <strong>Uso do TestSuite.py</strong> (4,263), a <strong>Correção Objetiva VPL</strong> (4,213) e as <strong>Provas e Simulados Paramétricos</strong> (4,075).</p>
<p>Entre os recursos com participação direta da IA, a <strong>Rubrica por IA em Simulados/Provas</strong> apresentou média 3,587 (<span class="math inline">\(p&lt;0,001\)</span>), enquanto o <strong><em>Feedback</em> Socrático no VPL</strong> obteve 3,388 (<span class="math inline">\(p=0,011\)</span>). Ambos foram avaliados acima do ponto neutro, embora ocupem posições inferiores no <em>ranking</em>. Já o <strong>Material Didático por IA</strong> apresentou média 3,087, mediana 3 e não diferiu significativamente do valor neutro (<span class="math inline">\(p=0,710\)</span>), caracterizando uma avaliação predominantemente neutra.</p>
<p>Os três recursos com <strong>participação direta da IA</strong> na geração de conteúdo, <em>feedback</em> ou rubricas ocuparam as três últimas posições do <em>ranking</em>:</p>
<ul>
<li><strong>Material Didático por IA (<a href="../apendice_d_gemini_notebook.html">Apêndice D</a>):</strong> média 3,087;</li>
<li><strong><em>Feedback</em> Socrático no VPL <span class="citation" data-cites="zampirolli2026intelligent">(<a href="../referencias.html#ref-zampirolli2026intelligent" role="doc-biblioref">Zampirolli et al., 2026</a>)</span>:</strong> média 3,388;</li>
<li><strong>Rubrica por IA em Simulados/Provas (<a href="#apendice-e-ia-avaliacao">Apêndice E</a>):</strong> média 3,587.</li>
</ul>
<p>No caso do <strong><em>feedback</em> socrático</strong>, a comparação com o estudo descrito em <span class="citation" data-cites="zampirolli2026intelligent">(<a href="../referencias.html#ref-zampirolli2026intelligent" role="doc-biblioref">Zampirolli et al., 2026</a>)</span> deve considerar as diferenças de contexto pedagógico. Na aplicação anterior, realizada em uma disciplina introdutória de <strong>Lógica de Programação</strong>, o <em>feedback</em> era gerado exclusivamente a partir do código submetido pelo estudante, sem comentários ou descrição do enunciado, seguido de um <em>prompt</em> socrático. Em PDI-VC, os problemas apresentam maior complexidade e envolvem o uso da biblioteca didática <code>morph.py</code>, introduzindo uma camada adicional de abstração e conhecimento específico do domínio.</p>
<p>Esse padrão é relevante para a discussão pedagógica, mas <strong>não permite atribuir as avaliações inferiores à utilização da IA</strong>. Os recursos diferem simultaneamente quanto ao objetivo pedagógico, à forma de interação, ao grau de autonomia, à complexidade das tarefas e ao momento de utilização. As diferenças observadas devem, portanto, ser interpretadas como características da avaliação dos recursos em seus respectivos contextos, e não como evidência isolada de um efeito causal da IA.</p>
</section>
<section id="comparações-múltiplas-pós-teste-de-conover" class="level3" data-number="F.5.3">
<h3 data-number="F.5.3" class="anchored" data-anchor-id="comparações-múltiplas-pós-teste-de-conover"><span class="header-section-number">F.5.3</span> Comparações múltiplas — Pós-teste de Conover</h3>
<p>Como o teste de Friedman apresentou resultado significativo, foi aplicado o pós-teste de <em>Conover</em> <span class="citation" data-cites="conover1971">(<a href="../referencias.html#ref-conover1971" role="doc-biblioref">Conover, 1971</a>)</span>, com correção de <em>Bonferroni</em> <span class="citation" data-cites="dunn1961">(<a href="../referencias.html#ref-dunn1961" role="doc-biblioref">Dunn, 1961</a>)</span>, para identificar quais pares de recursos diferem estatisticamente entre si. Os resultados são apresentados na <a href="#fig-q08-conover-heatmap" class="quarto-xref">Figura&nbsp;<span>F.1</span></a>.</p>
<div id="cell-fig-q08-conover-heatmap" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>Conover-Bonferroni calculado: N=80, k=10, pares=45, Friedman χ²=189.662, p=&lt;0,001</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-q08-conover-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-q08-conover-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="apendice_f_files/figure-html/fig-q08-conover-heatmap-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-q08-conover-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;F.1: Matriz de p-valores do pós-teste de Conover (correção de Bonferroni) para comparações par a par entre os dez recursos didáticos. Células em branco indicam ausência de diferença estatisticamente significativa (p ≥ 0,05).
</figcaption>
</figure>
</div>
</div>
</div>
<p>O <strong>Material Didático por IA (<code>Q08_02</code>)</strong>, gerado pelo <em>Gemini Notebook</em>, apresentou a menor média entre os dez recursos (<strong>3,087</strong>, ver <a href="#tbl-q08-ranking" class="quarto-xref">Tabela&nbsp;<span>F.12</span></a>) e diferiu significativamente de <strong>sete recursos</strong>:</p>
<div id="fd2d339f" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>Recursos com diferença significativa em relação a Q08_02:
  1. `Q08_01` (Livro Interativo)
  2. `Q08_03` (Simuladores Interativos)
  3. `Q08_04` (Resolução de EPs em Aula)
  4. `Q08_05` (Biblioteca morph.py)
  5. `Q08_06` (Provas e Simulados Paramétricos)
  6. `Q08_09` (Correção Objetiva VPL)
  7. `Q08_10` (Uso do TestSuite.py)</code></pre>
</div>
</div>
<p>Os resultados devem ser interpretados considerando a <strong>correção para comparações múltiplas</strong>. Assim, diferenças nas médias ou nas posições do <em>ranking</em> não implicam, por si só, diferenças estatisticamente significativas entre os recursos.</p>
</section>
</section>
<section id="ranking-agregado-por-frequência-de-seleção-dos-recursos-didáticos-q09" class="level2" data-number="F.6">
<h2 data-number="F.6" class="anchored" data-anchor-id="ranking-agregado-por-frequência-de-seleção-dos-recursos-didáticos-q09"><span class="header-section-number">F.6</span> <em>Ranking</em> agregado por frequência de seleção dos recursos didáticos — Q09</h2>
<p>A questão <code>Q09</code> utilizou um formato de <strong>seleção de preferência</strong>, no qual cada estudante deveria selecionar <strong>exatamente quatro recursos</strong> considerados mais eficazes para seu processo de estudo, entre as dez opções apresentadas. Não havia ordenação entre as alternativas escolhidas. Portanto, <code>Q09</code> não produz uma escala ordinal nem um <em>ranking</em> individual, mas <strong>frequências agregadas de seleção</strong>, a partir das quais foi construído o <em>ranking</em> apresentado na <a href="#tbl-ranking-q09" class="quarto-xref">Tabela&nbsp;<span>F.13</span></a>.</p>
<div class="cell" data-execution_count="17">
<div id="tbl-ranking-q09" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="17">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ranking-q09-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.13: <em>Ranking</em> agregado de preferência declarada dos recursos didáticos, construído pela frequência de seleção. Cada estudante selecionou exatamente quatro recursos, sem estabelecer ordem entre eles.
</figcaption>
<div aria-describedby="tbl-ranking-q09-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="17">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Posição</th>
<th style="text-align: left;">Recurso</th>
<th style="text-align: center;">Escolhas</th>
<th style="text-align: center;">Percentual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1º</td>
<td style="text-align: left;">EPs em Aula</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">77,5%</td>
</tr>
<tr class="even">
<td style="text-align: center;">2º</td>
<td style="text-align: left;">morph.py</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">73,8%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3º</td>
<td style="text-align: left;">Simuladores</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">56,2%</td>
</tr>
<tr class="even">
<td style="text-align: center;">4º</td>
<td style="text-align: left;">Livro Interativo</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">53,8%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5º</td>
<td style="text-align: left;">SEB Simulados</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">51,2%</td>
</tr>
<tr class="even">
<td style="text-align: center;">6º</td>
<td style="text-align: left;">TestSuite.py</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">41,2%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7º</td>
<td style="text-align: left;">VPL Casos Teste</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">26,2%</td>
</tr>
<tr class="even">
<td style="text-align: center;">8º</td>
<td style="text-align: left;">Gemini Audio/Visual</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7,5%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9º</td>
<td style="text-align: left;">IA Feedback VPL</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6,2%</td>
</tr>
<tr class="even">
<td style="text-align: center;">10º</td>
<td style="text-align: left;">IA Rubrica Provas</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6,2%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Participaram <strong>80 estudantes</strong>, resultando em <strong>320 seleções</strong> (<span class="math inline">\(80\times4\)</span>). A soma das frequências da <a href="#tbl-ranking-q09" class="quarto-xref">Tabela&nbsp;<span>F.13</span></a> também totaliza 320, confirmando a consistência da tabulação.</p>
<p>Os <strong>EPs em Aula</strong> foram o recurso mais selecionado (62 estudantes; 77,5%), seguidos pela <strong><code>morph.py</code></strong> (59; 73,8%), pelos <strong>Simuladores</strong> (45; 56,2%) e pelo <strong>Livro Interativo</strong> (43; 53,8%). Em contraste, os recursos com participação direta da IA na geração de conteúdo, <em>feedback</em> ou rubricas estiveram entre os menos selecionados: <strong>Gemini Audio/Visual</strong> (6; 7,5%), <strong>IA Feedback VPL</strong> (5; 6,2%) e <strong>IA Rubrica Provas</strong> (5; 6,2%).</p>
<p>Esse padrão é consistente com o observado em <code>Q08</code>, no qual recursos associados à <strong>prática guiada, à programação e à interação direta com as atividades da disciplina</strong> também receberam avaliações mais elevadas. A convergência entre as duas questões reforça a relevância desses recursos na percepção dos estudantes, embora <code>Q09</code> represente <strong>preferência declarada por seleção</strong>, e não intensidade de avaliação.</p>
</section>
<section id="avaliação-global-dos-recursos-didáticos-q10" class="level2" data-number="F.7">
<h2 data-number="F.7" class="anchored" data-anchor-id="avaliação-global-dos-recursos-didáticos-q10"><span class="header-section-number">F.7</span> Avaliação Global dos Recursos Didáticos — Q10</h2>
<p>A questão <code>Q10</code> (<code>Q10-GLOBAL_BLOCO3</code>) sintetiza a percepção dos estudantes sobre o conjunto de recursos didáticos avaliados no Bloco 3. A avaliação apresentou <strong>média de 4,075</strong> e <strong>mediana 4</strong>, indicando percepção global positiva.</p>
<div id="e5db8375" class="cell" data-execution_count="18">
<div class="cell-output cell-output-stdout">
<pre><code>Q10 -&gt; média: 4,075 | mediana: 4
Correlação Spearman (escore médio Q08 x Q10, N=80): rho = 0,519, &lt;0,001</code></pre>
</div>
</div>
<p>Para verificar a associação entre as avaliações específicas e essa percepção geral, foi calculado, para cada estudante, o <strong>escore médio dos dez itens de <code>Q08</code></strong>, posteriormente correlacionado com <code>Q10</code> pelo coeficiente de <em>Spearman</em> <span class="citation" data-cites="spearman1904">(<a href="../referencias.html#ref-spearman1904" role="doc-biblioref">Spearman, 1904</a>)</span>. Observou-se uma correlação <strong>positiva e moderada</strong> (<span class="math inline">\(\rho=0,519\)</span>, <span class="math inline">\(p&lt;0,001\)</span>), indicando que avaliações mais favoráveis do conjunto dos recursos estiveram associadas a avaliações globais mais positivas.</p>
<p>Essa associação evidencia coerência entre as avaliações específicas e a percepção geral, mas <strong>não permite inferir que algum recurso individualmente determine a avaliação de <code>Q10</code></strong>.</p>
</section>
<section id="confiabilidade-dos-recursos-didáticos" class="level2" data-number="F.8">
<h2 data-number="F.8" class="anchored" data-anchor-id="confiabilidade-dos-recursos-didáticos"><span class="header-section-number">F.8</span> Confiabilidade dos Recursos Didáticos</h2>
<p>A consistência interna dos dez itens de <code>Q08</code> foi avaliada pelo <span class="math inline">\(\alpha\)</span> de <em>Cronbach</em> <span class="citation" data-cites="cronbach1951">(<a href="../referencias.html#ref-cronbach1951" role="doc-biblioref">Cronbach, 1951</a>)</span>, obtendo-se:</p>
<div id="d1cd33ba" class="cell" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>Alfa de Cronbach (Q08_01-Q08_10, N=80): alpha = 0,842</code></pre>
</div>
</div>
<p>Esse valor indica <strong>boa consistência interna</strong> entre os itens, segundo critérios convencionais de interpretação, sugerindo associação adequada entre seus padrões de resposta.</p>
<p>Entretanto, os dez itens representam <strong>recursos pedagogicamente distintos</strong>, com diferentes finalidades, formatos e formas de utilização. Portanto, o <span class="math inline">\(\alpha\)</span> observado não implica que constituam uma única intervenção ou um construto unidimensional. O resultado deve ser interpretado como evidência de <strong>coerência das respostas no conjunto dos itens</strong>, sem pressupor homogeneidade pedagógica entre os recursos.</p>
</section>
<section id="diferenças-entre-turmas" class="level2" data-number="F.9">
<h2 data-number="F.9" class="anchored" data-anchor-id="diferenças-entre-turmas"><span class="header-section-number">F.9</span> Diferenças entre Turmas</h2>
<p>As avaliações dos recursos didáticos também foram comparadas entre as três turmas participantes — <strong>duas da graduação (DA1 e DA2) e uma da pós-graduação (MCC)</strong>.</p>
<p>Para a avaliação global <code>Q10</code>, o teste de <em>Kruskal–Wallis</em> apresentou <span class="math inline">\(H=4,714\)</span> e <span class="math inline">\(p=0,095\)</span>. Como <span class="math inline">\(p&gt;0,05\)</span>, <strong>não foi identificada diferença estatisticamente significativa entre as turmas</strong> ao nível de 5%. Assim, as eventuais diferenças descritivas entre os grupos não fornecem evidência suficiente de que a avaliação global dos recursos tenha diferido entre as turmas.</p>
<div id="982e6fb5" class="cell" data-execution_count="20">
<div class="cell-output cell-output-stdout">
<pre><code>Kruskal-Wallis Q10 por Turma (DA1, DA2, MCC):
  DA1: n=39
  DA2: n=30
  MCC: n=11
H = 4,714, 0,095</code></pre>
</div>
</div>
</section>
<section id="uso-transversal-e-integração-da-ia" class="level2" data-number="F.10">
<h2 data-number="F.10" class="anchored" data-anchor-id="uso-transversal-e-integração-da-ia"><span class="header-section-number">F.10</span> Uso Transversal e Integração da IA</h2>
<p>Enquanto o Bloco 3 avalia recursos didáticos específicos, o Bloco 4 investiga a percepção dos estudantes sobre a <strong>integração transversal da IA no processo de ensino e aprendizagem</strong>, conforme apresentado na <a href="#tbl-ia-transversal" class="quarto-xref">Tabela&nbsp;<span>F.14</span></a>. As estatísticas descritivas e os testes de diferença em relação ao ponto neutro da escala também são apresentados nessa tabela.</p>
<p>Os três itens apresentaram <strong>avaliações estatisticamente superiores ao ponto neutro (3,0)</strong>: <code>Q11</code> — Pensamento Crítico e Alucinações, média 3,450 (<span class="math inline">\(p=0,001\)</span>); <code>Q12</code> — Transversalidade Pedagógica, média 3,487 (<span class="math inline">\(p=0,003\)</span>); e <code>Q13</code> — Avaliação Geral da Integração de IA, média 3,625 (<span class="math inline">\(p&lt;0,001\)</span>). Em todos os casos, a mediana foi 4.</p>
<p>O resultado indica uma <strong>percepção globalmente positiva da integração da IA</strong>, embora com intensidade moderada e inferior às avaliações atribuídas à maioria dos recursos didáticos mais bem avaliados no Bloco 3.</p>
<div class="cell" data-execution_count="21">
<div id="tbl-ia-transversal" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="21">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ia-transversal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.14: Avaliação dos itens sobre o uso transversal e a integração da IA no processo de ensino e aprendizagem. Os valores de p referem-se ao teste de postos sinalizados de Wilcoxon para uma amostra, tendo 3,0 como valor de referência.
</figcaption>
<div aria-describedby="tbl-ia-transversal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="21">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 54%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Descrição</th>
<th style="text-align: center;">Média</th>
<th style="text-align: center;">Mediana</th>
<th style="text-align: center;">p vs.&nbsp;neutro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q11</code></td>
<td style="text-align: left;">Pensamento Crítico e Alucinações</td>
<td style="text-align: center;">3,450</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,001</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q12</code></td>
<td style="text-align: left;">Transversalidade Pedagógica</td>
<td style="text-align: center;">3,487</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,003</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Q13</code></td>
<td style="text-align: left;">GLOBAL_BLOCO4 - Avaliação Geral da Integração de IA</td>
<td style="text-align: center;">3,625</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A consistência interna dos itens <code>Q11</code> e <code>Q12</code> foi avaliada pelo <span class="math inline">\(\alpha\)</span> de <em>Cronbach</em> <span class="citation" data-cites="cronbach1951">(<a href="../referencias.html#ref-cronbach1951" role="doc-biblioref">Cronbach, 1951</a>)</span>, obtendo-se <strong>0,786</strong>. Embora indique associação interna adequada, o coeficiente deve ser interpretado com cautela, pois foi calculado com apenas dois itens e, nesse caso, depende diretamente da correlação entre eles.</p>
<p>A associação entre o escore conjunto de <code>Q11</code> e <code>Q12</code> e a avaliação global da integração da IA (<code>Q13</code>) foi <strong>forte e estatisticamente significativa</strong> (<span class="math inline">\(\rho=0,777\)</span>, <span class="math inline">\(p&lt;0,001\)</span>), indicando que estudantes com percepções mais favoráveis sobre os aspectos crítico e transversal da IA também tenderam a avaliar mais positivamente sua integração geral na disciplina.</p>
<p>Na comparação entre as turmas, não foi identificada diferença estatisticamente significativa na avaliação global <code>Q13</code> (<span class="math inline">\(H=3,380\)</span>, <span class="math inline">\(p=0,184\)</span>).</p>
<div id="ba3dbc25" class="cell" data-execution_count="22">
<div class="cell-output cell-output-stdout">
<pre><code>Cronbach (Q11+Q12, N=80): alpha = 0,786
Spearman (escore Q11+Q12 x Q13, N=80): rho = 0,777, &lt;0,001
Kruskal-Wallis Q13 por Turma: H = 3,380, 0,184</code></pre>
</div>
</div>
</section>
<section id="síntese-dos-resultados" class="level2" data-number="F.11">
<h2 data-number="F.11" class="anchored" data-anchor-id="síntese-dos-resultados"><span class="header-section-number">F.11</span> Síntese dos Resultados</h2>
<p>A <a href="#fig-boxplot-sintese-likert" class="quarto-xref">Figura&nbsp;<span>F.2</span></a> apresenta a distribuição das respostas dos <strong>21 itens <em>Likert</em></strong> do questionário PÓS, ordenados pela média decrescente. A visualização permite comparar conjuntamente a tendência central e a dispersão das avaliações em relação ao ponto neutro da escala.</p>
<div id="cell-fig-boxplot-sintese-likert" class="cell" data-execution_count="23">
<div class="cell-output cell-output-stdout">
<pre><code>Pior média: Q08_02 (Material Didático por IA) = 3,087
Itens sem evidência de diferença ao ponto neutro: Q08_02</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-boxplot-sintese-likert" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-sintese-likert-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="apendice_f_files/figure-html/fig-boxplot-sintese-likert-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-sintese-likert-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;F.2: Distribuição das respostas dos 21 itens <em>Likert</em> do questionário PÓS, ordenados pela média decrescente. O Material Didático por IA, gerado com o <em>Gemini Notebook</em>, apresentou a pior média entre os itens analisados.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Os resultados evidenciam três aspectos principais. Primeiro, <strong>atividades práticas, interativas e relacionadas à programação</strong> estiveram entre os recursos mais bem avaliados, padrão também observado nas preferências declaradas em <code>Q09</code>. Segundo, na análise pareada entre PRÉ e PÓS, <strong>não foi identificada evidência estatisticamente significativa de mudança</strong> em nenhuma das seis dimensões avaliadas pelo teste de <em>Wilcoxon</em>. Terceiro, a <strong>integração transversal da IA recebeu avaliação positiva</strong>, embora os recursos com participação direta da IA na geração de conteúdo, <em>feedback</em> ou rubricas tenham apresentado avaliações inferiores às dos recursos mais bem avaliados.</p>
<p>A análise longitudinal deve ser interpretada considerando o tamanho da <strong>amostra pareada de 15 estudantes</strong>. As diferenças identificadas nas amostras completas pelo teste de <em>Mann–Whitney U</em> representam diferenças entre os conjuntos de respondentes e, portanto, não permitem inferir evolução individual.</p>
<p>No Bloco 3, o teste de Friedman indicou diferenças estatisticamente significativas entre as avaliações dos dez recursos (<span class="math inline">\(\chi^2(9)=189,662\)</span>, <span class="math inline">\(p&lt;0,001\)</span>), com <span class="math inline">\(W=0,263\)</span> de Kendall. A convergência entre <code>Q08</code> e <code>Q09</code> destaca a valorização de <strong>prática guiada, programação, experimentação e interação</strong>.</p>
<p>Entre os 21 itens <em>Likert</em>, o <strong>Material Didático por IA (<code>Q08_02</code>)</strong>, produzido com o <em>Gemini Notebook</em>, apresentou a menor média (<strong>3,087</strong>) e foi o <strong>único item sem evidência estatística de diferença em relação ao ponto neutro</strong>. Esse resultado é compatível com a hipótese exploratória de que a percepção dos estudantes dependa não apenas da presença da IA, mas também de <strong>como ela é integrada à atividade pedagógica</strong>. Essa interpretação, entretanto, não permite estabelecer relação causal entre a forma de utilização da IA e as avaliações observadas.</p>
<section id="tabela-síntese-dos-resultados-estatísticos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="tabela-síntese-dos-resultados-estatísticos">Tabela Síntese dos Resultados Estatísticos</h3>
<p>Como síntese quantitativa, a <a href="#tbl-sintese-geral" class="quarto-xref">Tabela&nbsp;<span>F.15</span></a> reúne os <strong>21 itens <em>Likert</em></strong> dos Blocos 2, 3 e 4 do questionário PÓS, ordenados pela média decrescente. São apresentados, para cada item, a média, o desvio-padrão (DP), a mediana e o <em>p</em>-valor do teste de postos sinalizados de <em>Wilcoxon</em> para uma amostra, tendo <strong>3,0 como ponto neutro</strong> da escala. O nível de significância adotado foi de 5%.</p>
<p>Considerando <strong>N=80</strong> respostas válidas, <strong>20 dos 21 itens (95,2%) apresentaram evidência estatística de avaliação superior ao ponto neutro</strong>. A única exceção foi <code>Q08_02</code> — Material Didático por IA — cuja média foi 3,087, sem diferença estatisticamente significativa em relação a 3,0 (<span class="math inline">\(p=0,710\)</span>).</p>
<p>A ordenação evidencia maior concentração das avaliações no conjunto de <strong>recursos práticos e interativos</strong>, enquanto os itens relacionados à integração transversal da IA e ao seu uso direto em determinados recursos apresentam médias mais moderadas. A tabela permite, assim, visualizar conjuntamente a distribuição das avaliações entre competências, recursos didáticos e integração da IA, sem pressupor que essas categorias constituam um único construto.</p>
<p>Esses resultados têm caráter <strong>descritivo e inferencial em relação ao ponto neutro</strong>, não permitindo estabelecer relações causais entre as características dos recursos e as avaliações atribuídas pelos estudantes.</p>
<div class="cell" data-execution_count="32">
<div class="cell-output cell-output-stdout">
<pre><code>20 de 21 itens (95.2%) com evidência de deslocamento favorável (N=80).</code></pre>
</div>
<div id="tbl-sintese-geral" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="32">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sintese-geral-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.15: Síntese estatística dos itens <em>Likert</em> dos Blocos 2, 3 e 4, ordenada pela média decrescente. Os valores de p referem-se ao teste de postos sinalizados de Wilcoxon para uma amostra, tendo 3,0 como valor de referência.
</figcaption>
<div aria-describedby="tbl-sintese-geral-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="32">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 6%">
<col style="width: 38%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Bloco</th>
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Descrição resumida</th>
<th style="text-align: center;">Média</th>
<th style="text-align: center;">DP</th>
<th style="text-align: center;">Mediana</th>
<th style="text-align: center;">p vs.&nbsp;3,0</th>
<th style="text-align: center;">Sig.?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_04</code></td>
<td style="text-align: left;">Resolução de EPs em Aula</td>
<td style="text-align: center;">4,588</td>
<td style="text-align: center;">0,650</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Competências</td>
<td style="text-align: left;"><code>Q01</code></td>
<td style="text-align: left;">PÓS - Capacidade de Programação</td>
<td style="text-align: center;">4,562</td>
<td style="text-align: center;">0,760</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_03</code></td>
<td style="text-align: left;">Simuladores Interativos</td>
<td style="text-align: center;">4,362</td>
<td style="text-align: center;">0,846</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_05</code></td>
<td style="text-align: left;">Biblioteca morph.py</td>
<td style="text-align: center;">4,300</td>
<td style="text-align: center;">1,048</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_01</code></td>
<td style="text-align: left;">Livro Interativo</td>
<td style="text-align: center;">4,287</td>
<td style="text-align: center;">0,814</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_10</code></td>
<td style="text-align: left;">Uso do TestSuite.py</td>
<td style="text-align: center;">4,263</td>
<td style="text-align: center;">0,938</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_09</code></td>
<td style="text-align: left;">Correção Objetiva VPL</td>
<td style="text-align: center;">4,213</td>
<td style="text-align: center;">1,015</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Global — Competências</td>
<td style="text-align: left;"><code>Q07</code></td>
<td style="text-align: left;">GLOBAL_BLOCO2 - Avaliação Geral do Aprendizado</td>
<td style="text-align: center;">4,125</td>
<td style="text-align: center;">0,891</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_06</code></td>
<td style="text-align: left;">Provas e Simulados Paramétricos</td>
<td style="text-align: center;">4,075</td>
<td style="text-align: center;">1,077</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Global — Recursos Didáticos</td>
<td style="text-align: left;"><code>Q10</code></td>
<td style="text-align: left;">GLOBAL_BLOCO3 - Avaliação Geral dos Recursos Didáticos</td>
<td style="text-align: center;">4,075</td>
<td style="text-align: center;">0,823</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Competências</td>
<td style="text-align: left;"><code>Q05</code></td>
<td style="text-align: left;">PÓS - Autonomia com Bibliotecas</td>
<td style="text-align: center;">3,825</td>
<td style="text-align: center;">0,925</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Competências</td>
<td style="text-align: left;"><code>Q03</code></td>
<td style="text-align: left;">PÓS - Atuação Profissional</td>
<td style="text-align: center;">3,725</td>
<td style="text-align: center;">1,043</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Competências</td>
<td style="text-align: left;"><code>Q02</code></td>
<td style="text-align: left;">PÓS - Atuação Acadêmica</td>
<td style="text-align: center;">3,712</td>
<td style="text-align: center;">1,009</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Global — IA Transversal</td>
<td style="text-align: left;"><code>Q13</code></td>
<td style="text-align: left;">GLOBAL_BLOCO4 - Avaliação Geral da Integração de IA</td>
<td style="text-align: center;">3,625</td>
<td style="text-align: center;">1,236</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_08</code></td>
<td style="text-align: left;">Rubrica por IA em Simulados/Provas</td>
<td style="text-align: center;">3,587</td>
<td style="text-align: center;">1,099</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Competências</td>
<td style="text-align: left;"><code>Q04</code></td>
<td style="text-align: left;">PÓS - Fundamentos Matemáticos</td>
<td style="text-align: center;">3,538</td>
<td style="text-align: center;">1,043</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">&lt;0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IA Transversal</td>
<td style="text-align: left;"><code>Q12</code></td>
<td style="text-align: left;">Transversalidade Pedagógica</td>
<td style="text-align: center;">3,487</td>
<td style="text-align: center;">1,212</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,003</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">IA Transversal</td>
<td style="text-align: left;"><code>Q11</code></td>
<td style="text-align: left;">Pensamento Crítico e Alucinações</td>
<td style="text-align: center;">3,450</td>
<td style="text-align: center;">1,135</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,001</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Competências</td>
<td style="text-align: left;"><code>Q06</code></td>
<td style="text-align: left;">PÓS - Feedback por IA</td>
<td style="text-align: center;">3,438</td>
<td style="text-align: center;">1,330</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,007</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_07</code></td>
<td style="text-align: left;">Feedback Socrático no VPL</td>
<td style="text-align: center;">3,388</td>
<td style="text-align: center;">1,248</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0,011</td>
<td style="text-align: center;">Sim</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recursos Didáticos</td>
<td style="text-align: left;"><code>Q08_02</code></td>
<td style="text-align: left;">Material Didático por IA</td>
<td style="text-align: center;">3,087</td>
<td style="text-align: center;">1,361</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0,710</td>
<td style="text-align: center;">Não</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="principais-conclusões" class="level2" data-number="F.12">
<h2 data-number="F.12" class="anchored" data-anchor-id="principais-conclusões"><span class="header-section-number">F.12</span> Principais Conclusões</h2>
<p>Os resultados permitem sintetizar os principais achados da análise:</p>
<ol type="1">
<li><p><strong>Avaliação global positiva.</strong> Os recursos didáticos apresentaram avaliação favorável, com média de <strong>4,075</strong> e mediana 4 em <code>Q10</code>.</p></li>
<li><p><strong>Diferenciação entre os recursos.</strong> O teste de Friedman identificou diferenças estatisticamente significativas entre os dez recursos (<span class="math inline">\(\chi^2(9)=189,662\)</span>, <span class="math inline">\(p&lt;0,001\)</span>), com concordância moderada segundo o W de Kendall (<span class="math inline">\(W=0,263\)</span>).</p></li>
<li><p><strong>Predomínio de recursos práticos e interativos.</strong> A <strong>Resolução de EPs em Aula</strong>, os <strong>simuladores</strong> e a biblioteca <strong><code>morph.py</code></strong> estiveram entre os recursos mais bem avaliados e mais frequentemente selecionados em <code>Q09</code>, evidenciando a valorização de atividades de experimentação e programação.</p></li>
<li><p><strong>Ausência de evidência de mudança individual.</strong> No teste de <em>Wilcoxon</em> aplicado aos <strong>15 estudantes pareados</strong>, nenhuma das seis dimensões comparadas entre PRÉ e PÓS apresentou diferença estatisticamente significativa. Esse resultado deve ser considerado à luz do tamanho reduzido da amostra pareada.</p></li>
<li><p><strong>Percepção favorável da integração da IA.</strong> Os três itens do Bloco 4 apresentaram avaliações estatisticamente superiores ao ponto neutro. Entretanto, os recursos com participação direta da IA na geração de conteúdo, <em>feedback</em> ou rubricas tiveram avaliações mais moderadas do que diversos recursos práticos.</p></li>
<li><p><strong>Coerência entre avaliações específicas e globais.</strong> O escore médio de <code>Q08</code> apresentou correlação positiva e moderada com <code>Q10</code> (<span class="math inline">\(\rho=0,519\)</span>, <span class="math inline">\(p&lt;0,001\)</span>), enquanto <code>Q11</code> e <code>Q12</code> apresentaram associação forte com <code>Q13</code> (<span class="math inline">\(\rho=0,777\)</span>, <span class="math inline">\(p&lt;0,001\)</span>).</p></li>
<li><p><strong>Ausência de diferenças globais entre turmas.</strong> Não foram identificadas diferenças estatisticamente significativas entre as turmas na avaliação global dos recursos (<code>Q10</code>: <span class="math inline">\(p=0,095\)</span>) ou da integração da IA (<code>Q13</code>: <span class="math inline">\(p=0,184\)</span>).</p></li>
<li><p><strong>Consistência interna adequada.</strong> Os dez itens de <code>Q08</code> apresentaram <span class="math inline">\(\alpha=0,842\)</span>. Para <code>Q11</code> e <code>Q12</code>, obteve-se <span class="math inline">\(\alpha=0,786\)</span>, resultado que deve ser interpretado com cautela por se basear em apenas dois itens.</p></li>
</ol>
<p>Em conjunto, os resultados indicam que a percepção dos estudantes esteve associada sobretudo à <strong>forma de inserção dos recursos nas atividades de aprendizagem</strong>, com destaque para práticas guiadas, experimentação e programação. A participação direta da IA, por si só, não explica as diferenças observadas entre os recursos, que também se distinguem por finalidade, formato, interação, complexidade e momento de utilização.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Nota metodológica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os resultados devem ser interpretados como evidências de <strong>diferenças, associações e padrões de percepção</strong>, e não como demonstrações de causalidade. Em particular, as avaliações dos recursos com participação direta da IA não permitem inferir um efeito positivo ou negativo da tecnologia. Da mesma forma, diferenças entre as amostras completas PRÉ e PÓS não constituem evidência de evolução individual; para essa finalidade, foram considerados exclusivamente os estudantes pareados.</p>
</div>
</div>
</section>
<section id="avaliação-de-valência-das-respostas-abertas-q14-e-q15" class="level2" data-number="F.13">
<h2 data-number="F.13" class="anchored" data-anchor-id="avaliação-de-valência-das-respostas-abertas-q14-e-q15"><span class="header-section-number">F.13</span> Avaliação de Valência das Respostas Abertas — Q14 e Q15</h2>
<p>As questões abertas <code>Q14</code> e <code>Q15</code> complementam as avaliações estruturadas do questionário PÓS, permitindo analisar espontaneamente aspectos da experiência pedagógica. A <strong>análise temática</strong> identifica <em>quais</em> aspectos foram mencionados, enquanto a <strong>análise de valência</strong> caracteriza sua orientação avaliativa.</p>
<p>Como as questões possuem finalidades distintas — <code>Q14</code> focaliza <strong>ganhos percebidos de aprendizagem</strong>, enquanto <code>Q15</code> aborda <strong>dificuldades e possibilidades de aprimoramento</strong> —, seus resultados são analisados separadamente e não constituem medidas diretamente comparáveis de satisfação geral.</p>
<section id="unidade-de-análise-e-critérios" class="level3" data-number="F.13.1">
<h3 data-number="F.13.1" class="anchored" data-anchor-id="unidade-de-análise-e-critérios"><span class="header-section-number">F.13.1</span> Unidade de análise e critérios</h3>
<p>A unidade de análise foi a <strong>resposta completa</strong>, classificada como <strong>positiva, negativa, mista ou neutra</strong> conforme a orientação predominante. Os critérios adotados para cada categoria são apresentados na <a href="#tbl-criterios-valencia" class="quarto-xref">Tabela&nbsp;<span>F.16</span></a>. Quando uma resposta apresentava avaliações distintas sobre diferentes aspectos, realizou-se também o refinamento por tema.</p>
<div class="cell" data-execution_count="33">
<div id="tbl-criterios-valencia" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="33">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-criterios-valencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.16: Critérios de classificação da valência das respostas abertas (Q14/Q15).
</figcaption>
<div aria-describedby="tbl-criterios-valencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="33">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Código</th>
<th style="text-align: left;">Critério</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>POSITIVA</strong></td>
<td style="text-align: left;">Predominam benefício, aprovação ou melhoria percebida.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>NEGATIVA</strong></td>
<td style="text-align: left;">Predominam crítica, dificuldade ou ausência de benefício.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>MISTA</strong></td>
<td style="text-align: left;">Aspectos positivos e negativos relevantes coexistem explicitamente.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>NEUTRA</strong></td>
<td style="text-align: left;">A resposta apenas descreve ou identifica um elemento, sem avaliação suficiente para estabelecer polaridade.</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Foram analisadas <strong>40 respostas não vazias em <code>Q14</code></strong> e <strong>38 em <code>Q15</code></strong>, correspondendo, respectivamente, a <strong>50,0%</strong> e <strong>47,5%</strong> dos 80 respondentes do questionário PÓS, conforme apresentado na <a href="#tbl-resumo-q14-q15" class="quarto-xref">Tabela&nbsp;<span>F.17</span></a>. As respostas vazias foram excluídas.</p>
<p>A análise temática utilizou <strong>codificação múltipla</strong>, permitindo mais de um tema por resposta. Foram registradas <strong>44 menções temáticas em <code>Q14</code></strong> e <strong>59 em <code>Q15</code></strong>. Esses valores correspondem a ocorrências de temas e, portanto, podem ser superiores ao número de respostas analisadas.</p>
<div class="cell" data-execution_count="45">
<div id="tbl-resumo-q14-q15" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="45">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-resumo-q14-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.17: Síntese da unidade de análise: respostas não vazias e menções temáticas (codificação múltipla) em Q14 e Q15.
</figcaption>
<div aria-describedby="tbl-resumo-q14-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="45">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 34%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: center;">N respostas não vazias</th>
<th style="text-align: center;">% do total (N=80)</th>
<th style="text-align: center;">Menções temáticas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Q14</code></td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">50,0%</td>
<td style="text-align: center;">44</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Q15</code></td>
<td style="text-align: center;">38</td>
<td style="text-align: center;">47,5%</td>
<td style="text-align: center;">59</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="análise-temática-de-q14-maior-contribuição-da-ia" class="level3" data-number="F.13.2">
<h3 data-number="F.13.2" class="anchored" data-anchor-id="análise-temática-de-q14-maior-contribuição-da-ia"><span class="header-section-number">F.13.2</span> Análise temática de Q14 — Maior contribuição da IA</h3>
<p>A <a href="#tbl-analise-tematica-q14" class="quarto-xref">Tabela&nbsp;<span>F.18</span></a> apresenta a distribuição dos <strong>temas identificados nas respostas à <code>Q14</code></strong>, que solicitou aos estudantes a indicação da principal contribuição da IA para sua aprendizagem. A codificação permitiu registrar mais de um tema na mesma resposta; por isso, as frequências representam <strong>menções temáticas</strong>, e não necessariamente participantes distintos.</p>
<p>O tema mais frequente foi <strong>geração de material didático</strong>, abrangendo referências a livros, PDFs, vídeos, simuladores e <em>NotebookLM</em>, com <strong>23 menções (57,5%)</strong>. Em seguida, apareceram <strong>EPs e prática em geral</strong>, sem referência explícita à IA (17,5%), e <strong>feedback de IA nos EPs</strong> (15,0%). Menções a <em>feedback</em> ou rubricas em simulados e provas corresponderam a 10,0%.</p>
<p>Também foram identificadas manifestações que <strong>não reconheceram ganhos ou rejeitaram o uso de IA</strong> (5,0%), além de respostas <strong>não classificáveis ou inconclusivas</strong> (5,0%). Esses resultados indicam que a contribuição percebida da IA esteve associada principalmente à <strong>produção e disponibilização de materiais didáticos</strong>, seguida de aplicações voltadas ao <em>feedback</em> e à prática.</p>
<div class="cell" data-execution_count="46">
<div id="tbl-analise-tematica-q14" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="46">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-analise-tematica-q14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.18: Distribuição temática das percepções sobre a maior contribuição da IA (Q14).
</figcaption>
<div aria-describedby="tbl-analise-tematica-q14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="46">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 61%">
<col style="width: 14%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Eixo Temático / Categoria</th>
<th style="text-align: center;">Menções (n)</th>
<th style="text-align: center;">Frequência Relativa*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Geração de material (livro/PDF/vídeos/simuladores/NotebookLM)</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">57,5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">EPs/prática em geral (sem menção clara à IA)</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">17,5%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Feedback de IA nos EPs</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">15,0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Feedback/rubrica em simulados e provas</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">10,0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nenhum ganho / rejeita uso de IA</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">5,0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Não classificável / resposta não conclusiva</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">5,0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="principais-dificuldades-e-sugestões-de-ajuste-q15" class="level3" data-number="F.13.3">
<h3 data-number="F.13.3" class="anchored" data-anchor-id="principais-dificuldades-e-sugestões-de-ajuste-q15"><span class="header-section-number">F.13.3</span> Principais dificuldades e sugestões de ajuste — Q15</h3>
<p>A análise temática de <code>Q15</code> identificou as principais <strong>dificuldades percebidas e sugestões de ajuste metodológico</strong> apresentadas pelos estudantes. Como uma mesma resposta podia mencionar diferentes aspectos, foi utilizada codificação múltipla; portanto, as frequências correspondem a <strong>menções temáticas</strong>, e não ao número de respondentes. Os resultados são apresentados na <a href="#tbl-analise-tematica-q15" class="quarto-xref">Tabela&nbsp;<span>F.19</span></a>.</p>
<p>As menções mais frequentes referem-se ao <strong><em>feedback</em> por IA</strong> (12), às dificuldades relacionadas ao <strong>VPL e às restrições de rede da UFABC</strong> (11), à <strong>biblioteca <code>morph.py</code>/OpenCV</strong> (9) e ao <strong>SEB</strong> (8). Também foram mencionados o <strong>material gerado por IA</strong>, especialmente vídeos e <em>slides</em> (6), o <strong>tempo de provas e simulados</strong> (5) e outros aspectos relacionados à estrutura dos EPs e ao conteúdo (4).</p>
<p>Esses resultados complementam a avaliação quantitativa ao evidenciar <strong>aspectos concretos da experiência pedagógica que podem orientar ajustes metodológicos</strong>, especialmente em relação ao <em>feedback</em> automatizado, à infraestrutura de acesso e ao uso de ferramentas específicas da disciplina.</p>
<div class="cell" data-execution_count="47">
<div id="tbl-analise-tematica-q15" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="47">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-analise-tematica-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.19: Principais dificuldades e sugestões de ajustes metodológicos apontadas pelos estudantes (Q15).
</figcaption>
<div aria-describedby="tbl-analise-tematica-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="47">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 60%">
<col style="width: 15%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dificuldade / Sugestão de Ajuste</th>
<th style="text-align: center;">Menções (n)</th>
<th style="text-align: center;">Frequência Relativa*</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Feedback por IA</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">31,6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">VPL / restrição à rede da UFABC (emergente)</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">28,9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biblioteca (morph/opencv)</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">23,7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">SEB (ambiente seguro de provas)</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">21,1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Material gerado por IA (vídeos/slides/excesso) (emergente)</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">15,8%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tempo de prova/simulado</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">13,2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outro (estrutura dos EPs, conteúdo, etc.)</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">10,5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCTest</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7,9%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nenhuma dificuldade relevante</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2,6%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="síntese-da-análise-temática-de-q14-e-q15" class="level3" data-number="F.13.4">
<h3 data-number="F.13.4" class="anchored" data-anchor-id="síntese-da-análise-temática-de-q14-e-q15"><span class="header-section-number">F.13.4</span> Síntese da Análise Temática de <code>Q14</code> e <code>Q15</code></h3>
<p>A distribuição comparativa dos principais eixos temáticos identificados nas duas questões é apresentada na <a href="#fig-sintese-qualitativa-q14-q15" class="quarto-xref">Figura&nbsp;<span>F.3</span></a>. A visualização permite contrastar, de forma conjunta, os aspectos associados aos <strong>ganhos percebidos</strong> (<code>Q14</code>) e às <strong>dificuldades ou sugestões de ajuste</strong> (<code>Q15</code>).</p>
<p>Em <code>Q14</code>, predominam menções relacionadas à <strong>geração de materiais didáticos</strong>, enquanto <code>Q15</code> concentra maior diversidade de dificuldades, com destaque para <strong><em>feedback</em> por IA</strong>, <strong>VPL e restrições de rede</strong>, <strong>bibliotecas</strong> e <strong>SEB</strong>. Como a codificação temática foi múltipla, uma mesma resposta pode contribuir para mais de um eixo; portanto, as frequências representam <strong>menções temáticas</strong>, e não proporções exclusivas de respondentes.</p>
<div id="cell-fig-sintese-qualitativa-q14-q15" class="cell" data-execution_count="48">
<div class="cell-output cell-output-display">
<div id="fig-sintese-qualitativa-q14-q15" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sintese-qualitativa-q14-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="apendice_f_files/figure-html/fig-sintese-qualitativa-q14-q15-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sintese-qualitativa-q14-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;F.3: Distribuição comparativa dos principais eixos temáticos identificados nas questões abertas Q14 e Q15.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="resultados-globais-por-resposta" class="level3" data-number="F.13.5">
<h3 data-number="F.13.5" class="anchored" data-anchor-id="resultados-globais-por-resposta"><span class="header-section-number">F.13.5</span> Resultados globais por resposta</h3>
<p>A <span class="quarto-unresolved-ref">?tbl-valencia</span> apresenta a distribuição da <strong>valência global</strong> das respostas não vazias, considerando cada resposta completa como uma única unidade de análise.</p>
<p>Em <code>Q14</code>, predominam respostas <strong>positivas</strong> (80,0%), enquanto em <code>Q15</code> predominam respostas <strong>negativas</strong> (76,3%). Essa diferença decorre das finalidades distintas das questões: <code>Q14</code> aborda ganhos percebidos de aprendizagem, ao passo que <code>Q15</code> focaliza dificuldades e aspectos a serem ajustados. Portanto, a valência de <code>Q15</code> <strong>não representa uma avaliação global negativa da disciplina</strong>.</p>
</section>
<section id="refinamento-da-valência-por-tema" class="level3" data-number="F.13.6">
<h3 data-number="F.13.6" class="anchored" data-anchor-id="refinamento-da-valência-por-tema"><span class="header-section-number">F.13.6</span> Refinamento da valência por tema</h3>
<p>As <strong>8 respostas classificadas globalmente como mistas</strong> foram relidas para atribuir a valência especificamente aos temas mencionados. Esse procedimento alterou <strong>14 pares <code>(resposta, tema)</code></strong>, preservando, nos demais casos, a valência global da resposta.</p>
<div id="cb9db2d7" class="cell" data-execution_count="50">
<div class="cell-output cell-output-stdout">
<pre><code>Menções com valência refinada por releitura manual (diverge da valência global da resposta): 14</code></pre>
</div>
</div>
<p>Os resultados por tema são apresentados nas <a href="#tbl-valencia-categoria-q14" class="quarto-xref">Tabela&nbsp;<span>F.20</span></a> e <a href="#tbl-valencia-categoria-q15" class="quarto-xref">Tabela&nbsp;<span>F.21</span></a>. Como uma mesma resposta pode conter mais de um tema, esses valores correspondem a <strong>menções temáticas</strong>, e não ao número de respondentes.</p>
<div class="cell" data-execution_count="52">
<div id="tbl-valencia-categoria-q14" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="52">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-valencia-categoria-q14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.20: Valência (favorável/crítica/mista/neutra) por categoria temática em Q14 — maior contribuição da IA.
</figcaption>
<div aria-describedby="tbl-valencia-categoria-q14-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="52">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 54%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: center;">POSITIVA</th>
<th style="text-align: center;">NEGATIVA</th>
<th style="text-align: center;">MISTA</th>
<th style="text-align: center;">NEUTRA</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Geração de material (livro/PDF/vídeos/simuladores/NotebookLM)</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">EPs/prática em geral (sem menção clara à IA)</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Feedback de IA nos EPs</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Feedback/rubrica em simulados e provas</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nenhum ganho / rejeita uso de IA</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Não classificável / resposta não conclusiva</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="54">
<div id="tbl-valencia-categoria-q15" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="54">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-valencia-categoria-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;F.21: Valência (favorável/crítica/mista/neutra) por categoria temática em Q15 — dificuldades e ajustes metodológicos.
</figcaption>
<div aria-describedby="tbl-valencia-categoria-q15-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="54">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 53%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: center;">POSITIVA</th>
<th style="text-align: center;">NEGATIVA</th>
<th style="text-align: center;">MISTA</th>
<th style="text-align: center;">NEUTRA</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Feedback por IA</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">VPL / restrição à rede da UFABC (emergente)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biblioteca (morph/opencv)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">SEB (ambiente seguro de provas)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Material gerado por IA (vídeos/slides/excesso) (emergente)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tempo de prova/simulado</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Outro (estrutura dos EPs, conteúdo, etc.)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">MCTest</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nenhuma dificuldade relevante</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Em <code>Q14</code>, a <strong>geração de material</strong> concentra 22 menções positivas e uma mista, constituindo o principal tema associado aos ganhos percebidos. As demais categorias apresentam predominantemente valências positivas ou neutras; as duas menções de <strong>nenhum ganho/rejeição ao uso de IA</strong> foram negativas. Em <code>Q15</code>, predominam menções negativas, especialmente em <strong>feedback por IA</strong> (12) e <strong>VPL/restrição de rede</strong> (11). A categoria <strong>SEB</strong> reúne cinco menções negativas e três mistas, indicando que críticas ao ambiente seguro coexistiram, em alguns casos, com o reconhecimento de sua função.</p>
<p>A distribuição das valências por categoria é sintetizada visualmente na <a href="#fig-valencia-por-categoria" class="quarto-xref">Figura&nbsp;<span>F.4</span></a>. Esse refinamento permite distinguir críticas e avaliações favoráveis associadas a temas específicos, evitando atribuir automaticamente a mesma valência global a todos os aspectos mencionados em uma resposta.</p>
<div id="cell-fig-valencia-por-categoria" class="cell" data-execution_count="55">
<div class="cell-output cell-output-display">
<div id="fig-valencia-por-categoria" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-valencia-por-categoria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="apendice_f_files/figure-html/fig-valencia-por-categoria-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-valencia-por-categoria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;F.4: Valência das menções por categoria temática em Q14 e Q15 — barras empilhadas (favorável, crítica, mista, neutra).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="observações-metodológicas" class="level3" data-number="F.13.7">
<h3 data-number="F.13.7" class="anchored" data-anchor-id="observações-metodológicas"><span class="header-section-number">F.13.7</span> Observações metodológicas</h3>
<ul>
<li><p>As categorias <strong>POSITIVA</strong>, <strong>NEGATIVA</strong>, <strong>MISTA</strong> e <strong>NEUTRA</strong> foram mantidas separadas, sem agregação das respostas mistas às polaridades positiva ou negativa.</p></li>
<li><p>O refinamento por tema foi aplicado às respostas classificadas como <strong>mistas</strong>; nas demais, manteve-se a valência global para os temas identificados. Essa abordagem preserva a unidade da resposta e evita atribuir peso adicional a manifestações mais extensas.</p></li>
<li><p>A classificação foi realizada manualmente e possui caráter interpretativo. Não houve segundo codificador independente nem cálculo de concordância intercodificadores, como o <em>kappa</em> de Cohen. Os resultados devem, portanto, ser entendidos como uma <strong>codificação analítica documentada</strong>, e não como uma medida de concordância objetiva.</p></li>
<li><p>As frequências têm caráter <strong>descritivo</strong>. Dado o número de respostas não vazias e a baixa frequência de algumas categorias, os resultados caracterizam os padrões observados na amostra analisada, sem pretensão de generalização estatística para a população de estudantes.</p></li>
</ul>


<div id="refs" class="references csl-bib-body" data-entry-spacing="1" role="list" style="display: none">
<div id="ref-conover1971" class="csl-entry" role="listitem">
CONOVER, W. J. <strong>Practical Nonparametric Statistics</strong>. New York: John Wiley &amp; Sons, 1971.
</div>
<div id="ref-cronbach1951" class="csl-entry" role="listitem">
CRONBACH, Lee J. <a href="https://doi.org/10.1007/BF02310555">Coefficient Alpha and the Internal Structure of Tests</a>. <strong>Psychometrika</strong>, v. 16, n. 3, p. 297–334, 1951.
</div>
<div id="ref-dunn1961" class="csl-entry" role="listitem">
DUNN, Olive Jean. <a href="https://doi.org/10.1080/01621459.1961.10482090">Multiple Comparisons among Means</a>. <strong>Journal of the American Statistical Association</strong>, v. 56, n. 293, p. 52–64, 1961.
</div>
<div id="ref-friedman1937" class="csl-entry" role="listitem">
FRIEDMAN, Milton. <a href="https://doi.org/10.1080/01621459.1937.10503522">The Use of Ranks to Avoid the Assumption of Normality Implicit in the Analysis of Variance</a>. <strong>Journal of the American Statistical Association</strong>, v. 32, n. 200, p. 675–701, 1937.
</div>
<div id="ref-kendall1945" class="csl-entry" role="listitem">
KENDALL, M. G. <a href="https://doi.org/10.1093/biomet/33.3.239">The Treatment of Ties in Ranking Problems</a>. <strong>Biometrika</strong>, v. 33, n. 3, p. 239–251, 1945.
</div>
<div id="ref-kruskal1952" class="csl-entry" role="listitem">
KRUSKAL, William H.; WALLIS, W. Allen. <a href="https://doi.org/10.1080/01621459.1952.10483441">Use of Ranks in One-Criterion Variance Analysis</a>. <strong>Journal of the American Statistical Association</strong>, v. 47, n. 260, p. 583–621, 1952.
</div>
<div id="ref-mann1947" class="csl-entry" role="listitem">
MANN, Henry B.; WHITNEY, Donald R. <a href="https://doi.org/10.1214/aoms/1177730491">On a Test of Whether One of Two Random Variables Is Stochastically Larger than the Other</a>. <strong>The Annals of Mathematical Statistics</strong>, v. 18, n. 1, p. 50–60, 1947.
</div>
<div id="ref-spearman1904" class="csl-entry" role="listitem">
SPEARMAN, Charles. <a href="https://doi.org/10.2307/1412159">The Proof and Measurement of Association between Two Things</a>. <strong>The American Journal of Psychology</strong>, v. 15, n. 1, p. 72–101, 1904.
</div>
<div id="ref-wilcoxon1945" class="csl-entry" role="listitem">
WILCOXON, Frank. <a href="https://doi.org/10.2307/3001968">Individual Comparisons by Ranking Methods</a>. <strong>Biometrics Bulletin</strong>, v. 1, n. 6, p. 80–83, 1945.
</div>
<div id="ref-zampirolli2026intelligent" class="csl-entry" role="listitem">
ZAMPIROLLI, Francisco de Assis <em>et al.</em> <a href="https://doi.org/10.1002/cae.70132">Intelligent Feedback for Individualized Introductory Programming Exercises</a>. <strong>Computer Applications in Engineering Education</strong>, v. 34, n. 1, p. e70132, 2026.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../apendice_e_ia_avaliacao.html" class="pagination-link" aria-label="Uso de IA na Avaliação de Estudantes: o Projeto vpl-ai-feedback">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Uso de IA na Avaliação de Estudantes: o Projeto vpl-ai-feedback</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>