---
unnumbered: true
---

::: {.content-visible when-format="html"}
# Cataloging-in-Publication (CIP) Data {.unnumbered}

© 2026 Francisco de Assis Zampirolli, Federal University of ABC (UFABC). All rights reserved.

This book is licensed under the **Creative Commons Attribution-ShareAlike 4.0 International License**. Details at [creativecommons.org/licenses/by-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0).

**Graphic design:** Francisco de Assis Zampirolli\
**Cover:** Francisco de Assis Zampirolli, with AI support (Gemini and ChatGPT)

---

**CATALOGING-IN-PUBLICATION DATA**\
**UFABC LIBRARY SYSTEM**

> [CUTTER CODE] Zampirolli, Francisco de Assis
>
> Digital Image Processing and Computer Vision / Francisco de Assis Zampirolli -- Santo André, SP : Author's Edition, 2026.
>
> [xx], [NNN] p. : ill.
>
> ISBN: [ISBN TO BE DEFINED]
>
> 1. Digital Image Processing. 2. Computer Vision. 3. Mathematical Morphology. 4. Python. 5. Automatic Grading. 6. Moodle. I. Title.
>
> CDD [XX] ed. --- [CDD CODE]
:::

```{=latex}
% FICHA_CATALOGRAFICA_START
\thispagestyle{empty}
\noindent \textcopyright\ 2026 Francisco de Assis Zampirolli, Federal University of ABC (UFABC).\\
All rights reserved. \vspace{0.5cm}

\noindent This book is licensed under:\\
\hspace*{0.5cm}\textit{Creative Commons Attribution-ShareAlike 4.0 International License}\\
\hspace*{0.5cm}Details at: \href{[https://creativecommons.org/licenses/by-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0)}{creativecommons.org/licenses/by-sa/4.0} \vspace{0.5cm}

\noindent \textbf{Graphic design:} Francisco de Assis Zampirolli \\
\textbf{Cover:} Francisco de Assis Zampirolli, with AI support (Gemini and ChatGPT)

\vfill

\begin{center}
\hrule
\vspace{0.5cm}
{\small CATALOGING-IN-PUBLICATION DATA \\
UFABC LIBRARY SYSTEM}
\vspace{0.3cm}

\fbox{%
\parbox{0.92\linewidth}{%
\vspace{0.3cm}
\noindent [CUTTER CODE] \quad Zampirolli, Francisco de Assis \\
\hspace*{0.6cm} Digital Image Processing and Computer Vision / Francisco de Assis Zampirolli -- Santo André, SP : Author's Edition, 2026. \vspace{0.2cm}

\hspace*{0.6cm} [xx], [NNN] p. : ill. \vspace{0.2cm}

\hspace*{0.6cm} ISBN: [ISBN TO BE DEFINED] (1st Edition) \vspace{0.2cm}

\hspace*{0.6cm} 1. Digital Image Processing. 2. Computer Vision. 3. Mathematical Morphology. 4. Python. 5. Automatic Grading. 6. Moodle. I. Title. \vspace{0.2cm}

\hfill CDD [XX] ed. -- [CDD CODE]
\vspace{0.3cm}
}%
}
\end{center}
\vspace{1cm}
% FICHA_CATALOGRAFICA_END
```
