---
unnumbered: true
---

::: {.content-visible when-format="html"}
# Fiche Cataloguée {.unnumbered}

© 2026 Francisco de Assis Zampirolli, Universidade Federal do ABC (UFABC). Tous droits réservés.

Ce livre est sous la licence **Creative Commons Attribution-ShareAlike 4.0 International License**. Détails sur [creativecommons.org/licenses/by-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0).

**Conception graphique :** Francisco de Assis Zampirolli\
**Couverture :** Francisco de Assis Zampirolli, avec le soutien de l'IA (Gemini et ChatGPT)

---

**CATALOGAGE À LA SOURCE**\
**SYSTÈME DES BIBLIOTHÈQUES DE L'UNIVERSITÉ FÉDÉRALE DE L'ABC**

> [CODE CUTTER] Zampirolli, Francisco de Assis
>
> Traitement Numérique d'Images et Vision par Ordinateur / Francisco de Assis Zampirolli -- Santo André, SP : Édition de l'Auteur, 2026.
>
> [xx], [NNN] p. : ill.
>
> ISBN : [ISBN À DÉFINIR]
>
> 1. Traitement Numérique d'Images. 2. Vision par Ordinateur. 3. Morphologie Mathématique. 4. Python. 5. Correction Automatique. 6. Moodle. I. Titre.
>
> CDD [XX] éd. --- [CODE CDD]
:::

```{=latex}
% FICHA_CATALOGRAFICA_START
\thispagestyle{empty}
\noindent \textcopyright\ 2026 Francisco de Assis Zampirolli de l'Université Fédérale de l'ABC (UFABC).\\
Tous droits réservés. \vspace{0.5cm}

\noindent Ce livre est sous la licence :\\
\hspace*{0.5cm}\textit{Creative Commons Attribution-ShareAlike 4.0 International License}\\
\hspace*{0.5cm}Détails à l'adresse : \href{[https://creativecommons.org/licenses/by-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0)}{creativecommons.org/licenses/by-sa/4.0} \vspace{0.5cm}

\noindent \textbf{Conception graphique :} Francisco de Assis Zampirolli \\
\textbf{Couverture :} Francisco de Assis Zampirolli, avec le soutien de l'IA (Gemini et ChatGPT)

\vfill

\begin{center}
\hrule
\vspace{0.5cm}
{\small CATALOGAGE À LA SOURCE \\
SYSTÈME DES BIBLIOTHÈQUES DE L'UNIVERSITÉ FÉDÉRALE DE L'ABC}
\vspace{0.3cm}

\fbox{%
\parbox{0.92\linewidth}{%
\vspace{0.3cm}
\noindent [CODE CUTTER] \quad Zampirolli, Francisco de Assis \\
\hspace*{0.6cm} Traitement Numérique d'Images et Vision par Ordinateur / Francisco de Assis Zampirolli -- Santo André, SP : Édition de l'Auteur, 2026. \vspace{0.2cm}

\hspace*{0.6cm} [xx], [NNN] p. : ill. \vspace{0.2cm}

\hspace*{0.6cm} ISBN : [ISBN À DÉFINIR] (1ère Édition) \vspace{0.2cm}

\hspace*{0.6cm} 1. Traitement Numérique d'Images. 2. Vision par Ordinateur. 3. Morphologie Mathématique. 4. Python. 5. Correction Automatique. 6. Moodle. I. Titre. \vspace{0.2cm}

\hfill CDD [XX] éd. -- [CODE CDD]
\vspace{0.3cm}
}%
}
\end{center}
\vspace{1cm}
% FICHA_CATALOGRAFICA_END
```