---
unnumbered: true
---

::: {.content-visible when-format="html"}
# Ficha Catalográfica {.unnumbered}

© 2026 Francisco de Assis Zampirolli, Universidade Federal do ABC (UFABC). Todos os direitos reservados.

Este livro está sob a licença **Creative Commons Attribution-ShareAlike 4.0 International License**. Detalhes em [creativecommons.org/licenses/by-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0).

**Projeto gráfico:** Francisco de Assis Zampirolli\
**Capa:** Francisco de Assis Zampirolli (com suporte de IA - Gemini)

---

**CATALOGAÇÃO NA FONTE**\
**SISTEMA DE BIBLIOTECAS DA UNIVERSIDADE FEDERAL DO ABC**

> [CÓDIGO CUTTER] Zampirolli, Francisco de Assis
>
> Processamento Digital de Imagens e Visão Computacional / Francisco de Assis Zampirolli -- Santo André, SP : Edição do Autor, 2026.
>
> [xx], [NNN] p. : il.
>
> ISBN: [ISBN A DEFINIR]
>
> 1. Processamento Digital de Imagens. 2. Visão Computacional. 3. Morfologia Matemática. 4. Python. 5. Correção Automática. 6. Moodle. I. Título.
>
> CDD [XX] ed. --- [CÓDIGO CDD]
:::

```{=latex}
% FICHA_CATALOGRAFICA_START
\thispagestyle{empty}
\noindent \textcopyright\ 2026 Francisco de Assis Zampirolli da Universidade Federal do ABC (UFABC).\\
Todos os direitos reservados. \vspace{0.5cm}

\noindent Este livro está sob a Licença:\\
\hspace*{0.5cm}\textit{Creative Commons Attribution-ShareAlike 4.0 International License}\\
\hspace*{0.5cm}Detalhes no endereço: \href{[https://creativecommons.org/licenses/by-sa/4.0](https://creativecommons.org/licenses/by-sa/4.0)}{creativecommons.org/licenses/by-sa/4.0} \vspace{0.5cm}

\noindent \textbf{Projeto gráfico:} Francisco de Assis Zampirolli \\
\textbf{Capa:} Francisco de Assis Zampirolli (com suporte de IA - Gemini)

\vfill

\begin{center}
\hrule
\vspace{0.5cm}
{\small CATALOGAÇÃO NA FONTE \\
SISTEMA DE BIBLIOTECAS DA UNIVERSIDADE FEDERAL DO ABC}
\vspace{0.3cm}

\fbox{%
\parbox{0.92\linewidth}{%
\vspace{0.3cm}
\noindent [CÓDIGO CUTTER] \quad Zampirolli, Francisco de Assis \\
\hspace*{0.6cm} Processamento Digital de Imagens e Visão Computacional / Francisco de Assis Zampirolli -- Santo André, SP : Edição do Autor, 2026. \vspace{0.2cm}

\hspace*{0.6cm} [xx], [NNN] p. : il. \vspace{0.2cm}

\hspace*{0.6cm} ISBN: [ISBN A DEFINIR] (1ª Edição) \vspace{0.2cm}

\hspace*{0.6cm} 1. Processamento Digital de Imagens. 2. Visão Computacional. 3. Morfologia Matemática. 4. Python. 5. Correção Automática. 6. Moodle. I. Título. \vspace{0.2cm}

\hfill CDD [XX] ed. -- [CÓDIGO CDD]
\vspace{0.3cm}
}%
}
\end{center}
\vspace{1cm}
% FICHA_CATALOGRAFICA_END
``` 